### ISSUE TITLE
Unable to cast object of type 'EFCoreSecondLevelCacheInterceptor.EFTableRowsDataReader' to type 'Oracle.ManagedDataAccess.Client.OracleDataReader'.

### ISSUE THREAD

**Issue by maxborts** [VahidN/EFCoreSecondLevelCacheInterceptor#101]
# Summary of the issue

## Environment

```
.NET (Core) SDK version: 5.0
Microsoft.EntityFrameworkCore version: 5.0.3
EFCoreSecondLevelCacheInterceptor version: 2.4.1
Database: (e.g. SQL Server, SQLite, etc.) oracle 11g
Cache provider: (e.g. in-memory, redis, etc.)  in-memory
```

Hi VahidN;
I've got an error when I tried to update my Project from .net core3.1/EFCore3.1.8 to .Net 5.0/EF5.0.3

```

.Cacheable(CacheExpirationMode.Absolute, TimeSpan.FromHours(1))  <--error from this line

It  well worked on .net core3.1/EFCore3.1.8


```

## Output:

```
System.InvalidCastException:“Unable to cast object of type 'EFCoreSecondLevelCacheInterceptor.EFTableRowsDataReader' to type 'Oracle.ManagedDataAccess.Client.OracleDataReader'.”


Full Stack trace:
An exception occurred while iterating over the results of a query for context type 'XH.ICIS.Models.CISDATAContext'.
System.InvalidCastException: Unable to cast object of type 'EFCoreSecondLevelCacheInterceptor.EFTableRowsDataReader' to type 'Oracle.ManagedDataAccess.Client.OracleDataReader'.
   at Oracle.EntityFrameworkCore.Storage.Internal.OracleRelationalCommandBuilderFactory.OracleRelationalCommandBuilder.OracleRelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.InitializeReader(DbContext _, Boolean result)
   at Oracle.EntityFrameworkCore.Storage.Internal.OracleExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.MoveNext()System.InvalidCastException: Unable to cast object of type 'EFCoreSecondLevelCacheInterceptor.EFTableRowsDataReader' to type 'Oracle.ManagedDataAccess.Client.OracleDataReader'.
   at Oracle.EntityFrameworkCore.Storage.Internal.OracleRelationalCommandBuilderFactory.OracleRelationalCommandBuilder.OracleRelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.InitializeReader(DbContext _, Boolean result)
   at Oracle.EntityFrameworkCore.Storage.Internal.OracleExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.MoveNext()
```

**Comment by VahidN** [comment]
I don't know. It should work, because this is the signature of `OracleDataReader` and `EFTableRowsDataReader` can be converted to it.
```C#
 public sealed class OracleDataReader : DbDataReader 
```

```C#
public class EFTableRowsDataReader : DbDataReader
```

I am not running Oracle and I don't have any intention to install or test it. 
Just make sure you have updated all of your dependencies. It's better to run this command from the root of your solution to update all of your projects consistently:
```
dotnet restore
dotnet tool update --global dotnet-outdated-tool
dotnet outdated -u
dotnet restore
```

**Comment by bjarne-callewaert** [comment]
Hi,

We are having the same issue and we were able to narrow it down a little bit.

In our case, the .Cacheable(CacheExpirationMode.Absolute, TimeSpan.FromHours(1)) extension method is working correctly, until we use it on an query for an entity with a property that has a valueConverter (XDocument to string). On entities with 'more simple' valueConverters (stringToBool), this issue is not happening.

The failing query was working on EF Core 3.1, but since the upgrade to EF Core 5 it crashed.

I thought it was an [issue with the Oracle Data Provider](https://community.oracle.com/tech/developers/discussion/4482212/invalid-cast-exception-when-using-xdocument-valueconverter-and-efcoresecondlevelcacheinterceptor#latest
), but they redirected me to this issue.

Would it be possible to have another look at this?

**Comment by Aleksaas** [comment]
I have the same issue after upgrading EF Core to 3.1.3 and Oracle.EntityFrameworkCore to 3.19.110.

**Comment by maxborts** [comment]
Hi @VahidN 
the last workable version is Oracle.EntityFrameworkCore 3.19.80
does there any solution exist  with this issues?
thanks

**Comment by morales-franco** [comment]
Hi @VahidN @maxborts did you guys find any fix for this issue ? the current workaround is use EF Core 3.19.80 ?

**Comment by BggClr** [comment]
Have pretty same issue with Microsoft.Data.SqlClient.SqlDataReader.
Once I've added custom converter - **Unable to cast object of type 'EFCoreSecondLevelCacheInterceptor.EFTableRowsDataReader' to type 'Microsoft.Data.SqlClient.SqlDataReader'** issue appeared.
Microsoft.EntityFrameworkCore 7.0.10
Microsoft.EntityFrameworkCore.SqlServer 7.0.10
EasyCaching.Serialization.MessagePack 1.9.0
EFCoreSecondLevelCacheInterceptor 3.9.2
