### ISSUE TITLE
StackExchange.Redis.RedisTimeoutException: Timeout performing SETEX 

### ISSUE THREAD

**Issue by Simonl9l** [VahidN/EFCoreSecondLevelCacheInterceptor#102]
I have a process that is making over 1000 async http requests to a micro service running EF Core (3.1.10) with the second level cache setup with no additional configuration.

Unfortunately I have limited knowledge of Redis (but learning), any hints to point me in the right direction appreciated. The Redis cluster is hardly loaded.

After the first few hundred requests I get the exception below:

## Environment

```
.NET (Core) SDK version: 3.1.404
Microsoft.EntityFrameworkCore version: 3.1.10
EFCoreSecondLevelCacheInterceptor version: 2.1.0 
Database: (e.g. SQL Server, SQLite, etc.) AWS Aurora RDS MySql (via Pomelo)
Cache provider: (e.g. in-memory, redis, etc.): Redis
```

## Example code/Steps to reproduce:

```C#
 services.AddEFSecondLevelCache(options =>
            {
                options.UseEasyCachingCoreProvider(
                    providerName,
                    CacheExpirationMode.Sliding, 
                    TimeSpan.FromMinutes(5),
                    false).DisableLogging(configuration["ASPNETCORE_ENVIRONMENT"] == "Production");
                options.CacheAllQueries(CacheExpirationMode.Sliding, TimeSpan.FromMinutes(5));
            });

            services.AddEasyCaching(option =>
            {
                var endpoints = services.BuildServiceProvider().GetRequiredService<RedisEndpoints>().Endpoints;
                
                option.UseRedis(config =>
                {
                    config.DBConfig.AllowAdmin = true;
                    endpoints.ForEach(endpoint => config.DBConfig.Endpoints.Add(new ServerEndPoint(endpoint.Host, endpoint.Port)));
                }, providerName);
            });
```

## Output:

```
StackExchange.Redis.RedisTimeoutException: Timeout performing SETEX (5000ms), next: SETEX Accounts, inst: 0, qu: 0, qs: 1, aw: False, rs: ReadAsync, ws: Idle, in: 5, in-pipe: 0, out-pipe: 0, serverEndpoint: 10.0.0.201:6379, mc: 1/1/0, mgr: 10 of 10 available, clientName: SMBP-16, PerfCounterHelperkeyHashSlot: 885, IOCP: (Busy=0,Free=1000,Min=16,Max=1000), WORKER: (Busy=49,Free=32718,Min=16,Max=32767), v: 2.2.4.27433 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)
   at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in /_/src/StackExchange.Redis/ConnectionMultiplexer.cs:line 2809
   at StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in /_/src/StackExchange.Redis/RedisBase.cs:line 54
   at StackExchange.Redis.RedisDatabase.StringSet(RedisKey key, RedisValue value, Nullable`1 expiry, When when, CommandFlags flags) in /_/src/StackExchange.Redis/RedisDatabase.cs:line 2536
   at EasyCaching.Redis.DefaultRedisCachingProvider.BaseSet[T](String cacheKey, T cacheValue, TimeSpan expiration)
   at EasyCaching.Core.EasyCachingAbstractProvider.Set[T](String cacheKey, T cacheValue, TimeSpan expiration)
   at EFCoreSecondLevelCacheInterceptor.EFEasyCachingCoreProvider.<>c__DisplayClass4_0.<InsertValue>b__0()
```

**Comment by Simonl9l** [comment]
seem per [this](https://stackoverflow.com/a/43054448) I may need to pass in `syncTimeout` - how is this achieved with the setup above?

**Comment by VahidN** [comment]
[Follow its setup here](https://github.com/dotnetcore/EasyCaching/blob/152cbe7bf44bfeac1a10a75546532fa356a6d047/sample/EasyCaching.Demo.Providers/Startup.cs#L38).

**Comment by Simonl9l** [comment]
Thanks!

**Comment by Simonl9l** [comment]
FYI to others

> [Follow its setup here](https://github.com/dotnetcore/EasyCaching/blob/152cbe7bf44bfeac1a10a75546532fa356a6d047/sample/EasyCaching.Demo.Providers/Startup.cs#L38).

needs `EFCoreSecondLevelCacheInterceptor` >= "2.4.1
