### ISSUE TITLE
Redis cache returns empty sequence

### ISSUE THREAD

**Issue by Erwin32** [VahidN/EFCoreSecondLevelCacheInterceptor#123]
# Summary of the issue
I can't seem to figure this one out if I am configuring the cache badly or... Anyway, the first time a simple select query goes through everything is fine and redis gets written into without issues as far as I can tell (I can get the key that is in log in the redis-cli to show data). The second time I get an exception, the cache reports a hit but then returns 0 rows and as such throws. Expected would be the single row that gets correctly returned when the query is against SQL.

## Environment

```
.NET (Core) SDK version: 5.0
Microsoft.EntityFrameworkCore version: 5.0.5
EFCoreSecondLevelCacheInterceptor version: 2.7.0
Database: SQL server but MySQL has same issue
Cache provider: EasyCaching.Redis 1.1.0 and redis in docker compose
```

## Example code/Steps to reproduce:
whole example solution that has this issue:
https://github.com/Erwin32/SecondLevelCacheInterceptorTest

Startup
```cs
public void ConfigureServices(IServiceCollection services)
        {
            services.AddControllers();

            services.AddEasyCaching(o =>
            {
                o.WithMessagePack("Pack");

                o.UseRedis(cfg =>
                {
                    cfg.EnableLogging = true;
                    cfg.SerializerName = "Pack";
                    cfg.DBConfig.Endpoints.Add(new ServerEndPoint{Host = "test-redis", Port = 6379});
                    cfg.DBConfig.AllowAdmin = true;
                    cfg.DBConfig.ConnectionTimeout = 10000;
                }, "DbRedis");
            });

            services.AddEFSecondLevelCache(o =>
            {
                o.UseEasyCachingCoreProvider("DbRedis", isHybridCache: false).DisableLogging(false);
                o.CacheAllQueries(CacheExpirationMode.Absolute, TimeSpan.FromMinutes(10));
            });

            services.AddDbContextPool<TestContext>((sp, o) =>
            {
                o.UseSqlServer("Server=host.docker.internal;Database=testdb;User Id=test;Password=test;");
                o.AddInterceptors(sp.GetRequiredService<SecondLevelCacheInterceptor>());
            });
        }
```
Context
```cs
public class TestContext : DbContext
    {
        public DbSet<Entry> Entries { get; set; }

        public TestContext(DbContextOptions options) : base(options)
        {
            
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Entry>(e =>
            {
                e.HasData(new List<Entry>{new Entry{Id = 1, Data = 1245, Name = "Test"}});
            });   
            
            base.OnModelCreating(modelBuilder);
        }
    }
```
TestingController
```cs
[ApiController]
    [Route("/")]
    public class TestController : ControllerBase
    {
        public TestContext Context { get; }

        public TestController(TestContext context)
        {
            Context = context;
        }

        [HttpGet]
        public IActionResult Get()
        {
            var data = Context.Entries.Single(x => x.Id == 1);

            return Ok(data);
        }
    }
```

## Output:

```
test-api_1    | info: EasyCaching.Redis.DefaultRedisCachingProvider[0]
test-api_1    |       Cache Hit : cachekey = BF0D4939
test-api_1    | fail: Microsoft.AspNetCore.Server.Kestrel[13]
test-api_1    |       Connection id "0HM8G0F5G10BO", Request id "0HM8G0F5G10BO:00000004": An unhandled exception was thrown by the application.
test-api_1    |       System.InvalidOperationException: Sequence contains no elements
test-api_1    |          at System.Linq.ThrowHelper.ThrowNoElementsException()
test-api_1    |          at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
test-api_1    |          at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
test-api_1    |          at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
test-api_1    |          at System.Linq.Queryable.Single[TSource](IQueryable`1 source, Expression`1 predicate)
test-api_1    |          at L2CacheTest.TestController.Get() in /src/L2CacheTest/TestController.cs:line 21
test-api_1    |          at lambda_method1(Closure , Object , Object[] )
test-api_1    |          at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionRes
ultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
test-api_1    |          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
test-api_1    |          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object&
state, Boolean& isCompleted)
test-api_1    |          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
test-api_1    |       --- End of stack trace from previous location ---
test-api_1    |          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
test-api_1    |          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
test-api_1    |          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
test-api_1    |       --- End of stack trace from previous location ---
test-api_1    |          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
test-api_1    |          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
test-api_1    |          at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
test-api_1    |          at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

**Comment by VahidN** [comment]
Have you tried putting the `WithMessagePack` [after the](https://github.com/dotnetcore/EasyCaching/blob/152cbe7bf44bfeac1a10a75546532fa356a6d047/sample/EasyCaching.Demo.Providers/Startup.cs#L42) `UseRedis`? ([based on this comment](https://github.com/dotnetcore/EasyCaching/issues/16#issuecomment-369262413))

**Comment by Erwin32** [comment]
I have changed the code to be like this in startup
```cs
services.AddEasyCaching(o =>
            {
                o.UseRedis(cfg =>
                {
                    cfg.EnableLogging = true;
                    cfg.SerializerName = "Pack";
                    cfg.DBConfig.Endpoints.Add(new ServerEndPoint{Host = "test-redis", Port = 6379});
                    cfg.DBConfig.AllowAdmin = true;
                    cfg.DBConfig.ConnectionTimeout = 10000;
                }, "DbRedis").WithMessagePack("Pack");;
            });
```

Still getting the same exception on cache hit.

**Comment by VahidN** [comment]
Fixed it via#https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/commit/172e1e76a83017f78c2fcdf1b5c533b057873888
