### ISSUE TITLE
System.InvalidCastException: Unable to cast object of type 'System.DateTime' to type 'System.DateTimeOffset'.

### ISSUE THREAD

**Issue by dikklop** [VahidN/EFCoreSecondLevelCacheInterceptor#131]
# Summary of the issue
When we have a `DateTimeOffset?` in our Entity, requests fail the second time.
The first time the entity is cached.
The cache item looks like this: 
```
"28": {
				"$type": "EFCoreSecondLevelCacheInterceptor.EFTableColumnInfo, EFCoreSecondLevelCacheInterceptor",
				"Ordinal": 28,
				"Name": "lockout_end",
				"DbTypeName": "datetimeoffset",
				"TypeName": "System.DateTimeOffset"
			}
```
So, it's stored correct with the right (Db)TypeName.

However when you run a request for the second time, it fails on an unexpected conversion.

```
System.InvalidCastException: Unable to cast object of type 'System.DateTime' to type 'System.DateTimeOffset'.
   at System.Data.Common.DbDataReader.GetFieldValue[T](Int32 ordinal)
   at lambda_method140(Closure , QueryContext , DbDataReader , ResultContext , SingleQueryResultCoordinator )
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
```

## Environment

```
.NET (Core) SDK version:  5.0.6
Microsoft.EntityFrameworkCore version: 5.0.6
EFCoreSecondLevelCacheInterceptor version: 3.0.0
Database: SQL Server 2019
Cache provider: Redis
```

## Example code/Steps to reproduce:

```
public class UserEntity
    {
        public int Id { get; set; }
        public bool IsDeleted { get; set; }
        public DateTimeOffset? LockoutEnd { get; set; }

//other properties removed for code example
            }

#pragma warning disable StringLiteralTypo
    internal static class UserMapping
    {
        public static void Map(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<UserEntity>(entity => {
                entity.HasKey(e => e.Id);

                entity.ToTable("users", "user_info");

                entity.Property(e => e.Id)
                      .HasColumnName("user_id");

                entity.Property(e => e.LockoutEnd)
                      .HasColumnName("lockout_end");

                entity.HasQueryFilter(e => !e.IsDeleted);
            });
        }
    }


UserEntity user = await _dbContext.Users
                                              .AsNoTracking()
                                              .Where(u => u.Id == userId)
                                              .Cacheable(CacheExpirationMode.Absolute, TimeSpan.FromDays(1))
                                              .FirstAsync();
```

## Output:

```
Exception message: System.InvalidCastException: Unable to cast object of type 'System.DateTime' to type 'System.DateTimeOffset'.
Full Stack trace: System.InvalidCastException: Unable to cast object of type 'System.DateTime' to type 'System.DateTimeOffset'.
   at System.Data.Common.DbDataReader.GetFieldValue[T](Int32 ordinal)
   at lambda_method140(Closure , QueryContext , DbDataReader , ResultContext , SingleQueryResultCoordinator )
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
   at Deviant.WebApi.Web.Features.Users.UsersController.TestUserCacheable(Int32 userId) in /Users/dikklop/Projects/deviant-api/WebApi/src/Web/Features/Users/UsersController.cs:line 192
   at lambda_method132(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at SoapCore.SoapEndpointMiddleware`1.Invoke(HttpContext httpContext, IServiceProvider serviceProvider)
   at SoapCore.SoapEndpointMiddleware`1.Invoke(HttpContext httpContext, IServiceProvider serviceProvider)
   at SoapCore.SoapEndpointMiddleware`1.Invoke(HttpContext httpContext, IServiceProvider serviceProvider)
   at SoapCore.SoapEndpointMiddleware`1.Invoke(HttpContext httpContext, IServiceProvider serviceProvider)
   at SoapCore.SoapEndpointMiddleware`1.Invoke(HttpContext httpContext, IServiceProvider serviceProvider)
   at SoapCore.SoapEndpointMiddleware`1.Invoke(HttpContext httpContext, IServiceProvider serviceProvider)
   at Deviant.WebApi.Web.Middleware.NotFound.NotFoundMiddleware.InvokeAsync(HttpContext context, StudiemeterDbContext dbContext, NotFoundHandlerStore handlerStore) in /Users/dikklop/Projects/deviant-api/WebApi/src/Web/Middleware/NotFound/NotFoundMiddleware.cs:line 50
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

Tried workaround:
```
foreach (var property in modelBuilder.Model.GetEntityTypes()
                                                 .SelectMany(t => t.GetProperties())
                                                 .Where(p => p.ClrType == typeof(DateTimeOffset))) {
                property.SetValueConverter(
                                           new ValueConverter<DateTimeOffset, DateTime>(
                                                                                        convertToProviderExpression: dateTimeOffset => dateTimeOffset.UtcDateTime,
                                                                                        convertFromProviderExpression: dateTime => new DateTimeOffset(dateTime)
                                                                                       ));
            }

            foreach (var property in modelBuilder.Model.GetEntityTypes()
                                                 .SelectMany(t => t.GetProperties())
                                                 .Where(p => p.ClrType == typeof(DateTimeOffset?))) {
                property.SetValueConverter(
                                           new ValueConverter<DateTimeOffset?, DateTime?>(
                                                                                          convertToProviderExpression: dateTimeOffset =>
                                                                                              DateTime.SpecifyKind(dateTimeOffset.GetValueOrDefault().UtcDateTime,
                                                                                                                   DateTimeKind.Utc),
                                                                                          convertFromProviderExpression: dateTime =>
                                                                                              new DateTimeOffset(dateTime.GetValueOrDefault())
                                                                                         ));

                //property.SetColumnType(nameof(Nullable<DateTime>));
            }
```

It seems to solve the problem in the caching mechanism, but it raises problems in the rest of the application.

**Comment by VahidN** [comment]
- You don't need that converter for the SQL Server provider. It's useful for the MySQL and SQLite which don't support `DateTimeOffset` natively.
- It's related to the caching provider that you are using it ([here](https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/issues/12) and [here](https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/issues/44) and [here](https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/issues/29)). [Try using `EasyCaching` with `MessagePack`](https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/blob/master/src/Tests/Issues/Issue123WithMessagePack/EFServiceProvider.cs#L52). It's more compact and it's faster.

**Comment by dikklop** [comment]
I tried your suggestion and used MessagePack. 
Unfortunately that results in:
```
MessagePack.MessagePackSerializationException: Failed to serialize EFCoreSecondLevelCacheInterceptor.EFCachedData value.
 ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.TypeInitializationException: The type initializer for 'FormatterCache`1' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'FormatterCache`1' threw an exception.
 ---> MessagePack.Internal.MessagePackDynamicObjectResolverException: can't find public constructor. type:System.DBNull
   at MessagePack.Internal.ObjectSerializationInfo.CreateOrNull(Type type, Boolean forceStringKey, Boolean contractless, Boolean allowPrivate)
   at MessagePack.Internal.DynamicObjectTypeBuilder.BuildType(DynamicAssembly assembly, Type type, Boolean forceStringKey, Boolean contractless)
   at MessagePack.Resolvers.DynamicContractlessObjectResolver.FormatterCache`1..cctor()
   --- End of inner exception stack trace ---
   at MessagePack.Resolvers.DynamicContractlessObjectResolver.GetFormatter[T]()
   at MessagePack.Resolvers.ContractlessStandardResolver.FormatterCache`1..cctor()
   --- End of inner exception stack trace ---
   at MessagePack.Resolvers.ContractlessStandardResolver.GetFormatter[T]()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at MessagePack.FormatterResolverExtensions.GetFormatterDynamic(IFormatterResolver resolver, Type type)
   at MessagePack.FormatterResolverExtensions.GetFormatterDynamicWithVerify(IFormatterResolver resolver, Type type)
   at MessagePack.Formatters.DynamicObjectTypeFallbackFormatter.Serialize(MessagePackWriter& writer, Object value, MessagePackSerializerOptions options)
   at MessagePack.Formatters.CollectionFormatterBase`4.Serialize(MessagePackWriter& writer, TCollection value, MessagePackSerializerOptions options)
   at MessagePack.Formatters.EFCoreSecondLevelCacheInterceptor_EFTableRowFormatter3.Serialize(MessagePackWriter& writer, EFTableRow value, MessagePackSerializerOptions options)
   at MessagePack.Formatters.CollectionFormatterBase`4.Serialize(MessagePackWriter& writer, TCollection value, MessagePackSerializerOptions options)
   at MessagePack.Formatters.EFCoreSecondLevelCacheInterceptor_EFTableRowsFormatter2.Serialize(MessagePackWriter& writer, EFTableRows value, MessagePackSerializerOptions options)
   at MessagePack.Formatters.EFCoreSecondLevelCacheInterceptor_EFCachedDataFormatter1.Serialize(MessagePackWriter& writer, EFCachedData value, MessagePackSerializerOptions options)
   at MessagePack.MessagePackSerializer.Serialize[T](MessagePackWriter& writer, T value, MessagePackSerializerOptions options)
   --- End of inner exception stack trace ---
   at MessagePack.MessagePackSerializer.Serialize[T](MessagePackWriter& writer, T value, MessagePackSerializerOptions options)
   at MessagePack.MessagePackSerializer.Serialize[T](T value, MessagePackSerializerOptions options, CancellationToken cancellationToken)
   at EasyCaching.Serialization.MessagePack.DefaultMessagePackSerializer.Serialize[T](T value)
   at EasyCaching.Redis.DefaultRedisCachingProvider.BaseSet[T](String cacheKey, T cacheValue, TimeSpan expiration)
   at EasyCaching.Core.EasyCachingAbstractProvider.Set[T](String cacheKey, T cacheValue, TimeSpan expiration)
   at EFCoreSecondLevelCacheInterceptor.EFEasyCachingCoreProvider.<>c__DisplayClass5_0.<InsertValue>b__0() in D:\Prog\1398\EFCoreSecondLevelCacheInterceptor\src\EFCoreSecondLevelCacheInterceptor\EFEasyCachingCoreProvider.cs:line 90
   at EFCoreSecondLevelCacheInterceptor.ReaderWriterLockProvider.TryWriteLocked(Action action, Int32 timeout) in D:\Prog\1398\EFCoreSecondLevelCacheInterceptor\src\EFCoreSecondLevelCacheInterceptor\ReaderWriterLockProvider.cs:line 81
   at EFCoreSecondLevelCacheInterceptor.EFEasyCachingCoreProvider.InsertValue(EFCacheKey cacheKey, EFCachedData value, EFCachePolicy cachePolicy) in D:\Prog\1398\EFCoreSecondLevelCacheInterceptor\src\EFCoreSecondLevelCacheInterceptor\EFEasyCachingCoreProvider.cs:line 63
   at EFCoreSecondLevelCacheInterceptor.DbCommandInterceptorProcessor.ProcessExecutedCommands[T](DbCommand command, DbContext context, T result) in D:\Prog\1398\EFCoreSecondLevelCacheInterceptor\src\EFCoreSecondLevelCacheInterceptor\DbCommandInterceptorProcessor.cs:line 100
   at EFCoreSecondLevelCacheInterceptor.SecondLevelCacheInterceptor.ReaderExecutedAsync(DbCommand command, CommandExecutedEventData eventData, DbDataReader result, CancellationToken cancellationToken) in D:\Prog\1398\EFCoreSecondLevelCacheInterceptor\src\EFCoreSecondLevelCacheInterceptor\SecondLevelCacheInterceptor.cs:line 168
   at Microsoft.EntityFrameworkCore.Diagnostics.RelationalLoggerExtensions.CommandReaderExecutedAsync(IDiagnosticsLogger`1 diagnostics, IRelationalConnection connection, DbCommand command, DbContext context, Guid commandId, Guid connectionId, DbDataReader methodResult, DateTimeOffset startTime, TimeSpan duration, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(DbContext _, Boolean result, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
   at Deviant.WebApi.Web.Features.Users.UsersController.TestUserCacheable(Int32 userId) in /Users/dikklop/Projects/deviant-api/WebApi/src/Web/Features/Users/UsersController.cs:line 192
   at lambda_method132(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at SoapCore.SoapEndpointMiddleware`1.Invoke(HttpContext httpContext, IServiceProvider serviceProvider)
   at SoapCore.SoapEndpointMiddleware`1.Invoke(HttpContext httpContext, IServiceProvider serviceProvider)
   at SoapCore.SoapEndpointMiddleware`1.Invoke(HttpContext httpContext, IServiceProvider serviceProvider)
   at SoapCore.SoapEndpointMiddleware`1.Invoke(HttpContext httpContext, IServiceProvider serviceProvider)
   at SoapCore.SoapEndpointMiddleware`1.Invoke(HttpContext httpContext, IServiceProvider serviceProvider)
   at SoapCore.SoapEndpointMiddleware`1.Invoke(HttpContext httpContext, IServiceProvider serviceProvider)
   at Deviant.WebApi.Web.Middleware.NotFound.NotFoundMiddleware.InvokeAsync(HttpContext context, StudiemeterDbContext dbContext, NotFoundHandlerStore handlerStore) in /Users/dikklop/Projects/deviant-api/WebApi/src/Web/Middleware/NotFound/NotFoundMiddleware.cs:line 50
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

**Comment by VahidN** [comment]
`DbNull` [is discussed here](https://github.com/neuecc/MessagePack-CSharp/issues/129). [You can set those settings here](https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/blob/master/src/Tests/Issues/Issue123WithMessagePack/EFServiceProvider.cs#L65).

**Comment by dikklop** [comment]
Thanks for pointing me to the right direction. The problem has been solved by implementing a custom DBNull formatter
