### ISSUE TITLE
Does the library support Multi-table queries, across navigation properties?

### ISSUE THREAD

**Issue by silentbobbert** [VahidN/EFCoreSecondLevelCacheInterceptor#136]
# Summary of the issue

Does the library support querying across EF navigation properties, such that table joins for multiple entities are supported?

Full disclosure - I own a Nuget package for EFCache.Redis (https://github.com/silentbobbert/EFCache.Redis , which extends EFCache (https://github.com/moozzyk/EFCache) so I am reasonably familiar with second level caching within EF.

In the packages I mention, the SQL query string, for example (not a real example):

```
SELECT t1.Id, t1.Name, t2.OrderId
FROM dbo.Customer t1
INNER JOIN dbo.Orders t2 ON t1.Id = t2.CustomerId
WHERE t1.CustomerId = @p1 and t2.OrderDate > @p2
```
Is used (either directly for short strings, or a hash for longer ones) - and the entity sets from Customer and Orders tables are cached in the cache provider. If a second query came in for a Customer or Order, it could be satisfied by these cached objects.

If the same SQL query string is generated and p1 and p2 have the same values, and the results are still within their sliding and absolute expiry windows, the objects are deserialised from cache and returned as entities. If individual entities from within this result sets are invalidated by updates, it would invalidate the results of this query, plus a query directly requesting just this entity.

I was hoping to use your package as a more direct drop in replacement for the two I mentioned, as they only support EF6+, and not EF Core, but after initial setup I ran into this issue immediately.

## Environment

```
.NET (Core) SDK version: net5.0 (5.0.301)
Microsoft.EntityFrameworkCore version:  5.0.6
EFCoreSecondLevelCacheInterceptor version: 3.1.1
Database: (e.g. SQL Server, SQLite, etc.) MS SQL Server (docker compose)
Cache provider: (e.g. in-memory, redis, etc.) Redis (docker compose)
```

## Example code/Steps to reproduce:

```
var indices = await
   _dbContext.Indices
   .Include(i => i.User.ApplicationRoles)
       .ThenInclude(ar => ar.Role)
          .ThenInclude(r => r.Permissions)
   .AsNoTracking()
   .Where(i => i.ApplicationId == applicationId && i.CustomerId == customerId && i.UserId == userId)
   .Cacheable(CacheExpirationMode.Sliding, TimeSpan.FromMinutes(5))
   .ToArrayAsync()
   .ConfigureAwait(false);
```
## Output:

This code works on the first invocation, while the results are not cached. On immediate 2nd invocation, I get an exception 
`The underlying reader doesn't have as many fields as expected. Expected: 17, actual: 0.`

```
   at Microsoft.EntityFrameworkCore.Query.Internal.BufferedDataReader.BufferedDataRecord.InitializeFields()
   at Microsoft.EntityFrameworkCore.Query.Internal.BufferedDataReader.BufferedDataRecord.InitializeAsync(DbDataReader reader, IReadOnlyList`1 columns, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.BufferedDataReader.InitializeAsync(IReadOnlyList`1 columns, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.BufferedDataReader.InitializeAsync(IReadOnlyList`1 columns, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(DbContext _, Boolean result, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementationAsync[TState,TResult](Func`4 operation, Func`4 verifySucceeded, TState state, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementationAsync[TState,TResult](Func`4 operation, Func`4 verifySucceeded, TState state, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToArrayAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at ICT.AuthZ.InformationService.Api.Services.InformationDataService.GetPermsFromIndex(Guid applicationId, Guid customerId, Guid userId) in C:\Source\Repos\New_AuthZ\src\ICT.AuthZ.InformationService.Api\Services\InformationDataService.cs:line 27
```

**Comment by VahidN** [comment]
I have some tests about this subject [here](https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/blob/master/src/Tests/EFCoreSecondLevelCacheInterceptor.Tests/SecondLevelCacheInterceptorBasicTests.cs#L51) and it works with `Include`s and `Then Include`s. If it doesn't work for you, first try the in-memory cache, if it worked, it means your Redis cache settings are wrong.

**Comment by silentbobbert** [comment]
Thanks, I tried it with the in-memory cache like you suggested, and it works.

```
            var providerName = "Redis";
            services.AddEFSecondLevelCache(options =>
            {
                options.UseEasyCachingCoreProvider(providerName, isHybridCache: false)
                    .DisableLogging(true)
                    .UseCacheKeyPrefix("EF_");

                options.CacheAllQueries(CacheExpirationMode.Absolute, TimeSpan.FromMinutes(30));
            });

            services.AddEasyCaching(options =>
            {
                options
                    .WithProtobuf("proto")
                    .UseRedis(config =>
                    {
                        config.SerializerName = "proto";
                        config.DBConfig.AllowAdmin = true;
                        config.DBConfig.SyncTimeout = 10000;
                        config.DBConfig.AsyncTimeout = 10000;
                        config.DBConfig.Endpoints.Add(new ServerEndPoint("ict.bsp.redis", 6379));
                    }, providerName);
            });
```

I had setup Redis to use Protobuf as the serializer, after getting exceptions from the SDK about using the Binary serializer not being supported by default any longer.

So you think switching to message-pack might be the way to go? I will try that and let you know.

**Comment by silentbobbert** [comment]
Thanks @VahidN! The link you provided gave me working config. My queries are now being cached and deserialised as expected.

**Comment by chungonion** [comment]
Thanks @VahidN for the messagepack solution. Just one suggestion here, will that be possible to also bundle that class in future release so that others would able to find that instantly? 

Anyway thank you for your effort. It is a great package =] cheers =]
