### ISSUE TITLE
Issue with EasyCaching and Redis

### ISSUE THREAD

**Issue by c5racing** [VahidN/EFCoreSecondLevelCacheInterceptor#142]
# Summary of the issue
I'm trying to wire in EasyCaching and Redis.  BinaryFormatting is obsolete in .net Core 6, https://www.giters.com/dotnetcore/EasyCaching/issues/265 so I'm using the Protobuf serializer https://easycaching.readthedocs.io/en/latest/ProtoBuf/  I either receive and error that "BinaryFormatter serialization and deserialization are disabled within this application." when making the first DBContext call or "InvalidOperationException: Sequence contains no matching element" when this code is called "o.AddInterceptors(sp.GetRequiredService<SecondLevelCacheInterceptor>());" depending when I indicate the serialization being used.

## Environment

```
.NET (Core) SDK version: 6.0
Microsoft.EntityFrameworkCore version:  6.0
EFCoreSecondLevelCacheInterceptor version:  3.2.2
Database: PostgreSQL
Cache provider: Redis
```

## Example Code 1:

```
  services.AddEasyCaching(option =>
           {
                option.UseRedis(config =>
                {
                    config.DBConfig.AllowAdmin = true;
                    config.DBConfig.SyncTimeout = 10000;
                    config.DBConfig.AsyncTimeout = 10000;
                    config.DBConfig.Endpoints.Add(new EasyCaching.Core.Configurations.ServerEndPoint("redis", 6379));
                }, "DbRedis").WithProtobuf();
            });
			
			services.AddEFSecondLevelCache(options =>
            {
                options.UseEasyCachingCoreProvider("DbRedis", CacheExpirationMode.Absolute, TimeSpan.FromMinutes(30), isHybridCache: false).DisableLogging(true).UseCacheKeyPrefix("EF_");
            });
			
			services.AddDbContext<ConfigurationDbContext>((sp, o) =>
            {
                o.UseNpgsql(connectionString);
                o.AddInterceptors(sp.GetRequiredService<SecondLevelCacheInterceptor>());
            });
```

## Output Code 1:

```
BinaryFormatter serialization and deserialization are disabled within this application.
Exception message:
   System.NotSupportedException: BinaryFormatter serialization and deserialization are disabled within this application. See https://aka.ms/binaryformatter for more information.
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Serialize(Stream serializationStream, Object graph)
   at EasyCaching.Core.Serialization.DefaultBinaryFormatterSerializer.Serialize[T](T value)
   at EasyCaching.Redis.DefaultRedisCachingProvider.BaseSet[T](String cacheKey, T cacheValue, TimeSpan expiration)
   at EasyCaching.Core.EasyCachingAbstractProvider.Set[T](String cacheKey, T cacheValue, TimeSpan expiration)
   at EFCoreSecondLevelCacheInterceptor.EFEasyCachingCoreProvider.<>c__DisplayClass5_0.<InsertValue>b__0() in D:\Prog\1398\EFCoreSecondLevelCacheInterceptor\src\EFCoreSecondLevelCacheInterceptor\EFEasyCachingCoreProvider.cs:line 65
   at EFCoreSecondLevelCacheInterceptor.ReaderWriterLockProvider.TryWriteLocked(Action action, Int32 timeout) in D:\Prog\1398\EFCoreSecondLevelCacheInterceptor\src\EFCoreSecondLevelCacheInterceptor\ReaderWriterLockProvider.cs:line 81
   at EFCoreSecondLevelCacheInterceptor.EFEasyCachingCoreProvider.InsertValue(EFCacheKey cacheKey, EFCachedData value, EFCachePolicy cachePolicy) in D:\Prog\1398\EFCoreSecondLevelCacheInterceptor\src\EFCoreSecondLevelCacheInterceptor\EFEasyCachingCoreProvider.cs:line 63
   at EFCoreSecondLevelCacheInterceptor.DbCommandInterceptorProcessor.ProcessExecutedCommands[T](DbCommand command, DbContext context, T result) in D:\Prog\1398\EFCoreSecondLevelCacheInterceptor\src\EFCoreSecondLevelCacheInterceptor\DbCommandInterceptorProcessor.cs:line 100
   at EFCoreSecondLevelCacheInterceptor.SecondLevelCacheInterceptor.ReaderExecutedAsync(DbCommand command, CommandExecutedEventData eventData, DbDataReader result, CancellationToken cancellationToken) in D:\Prog\1398\EFCoreSecondLevelCacheInterceptor\src\EFCoreSecondLevelCacheInterceptor\SecondLevelCacheInterceptor.cs:line 187
   at Microsoft.EntityFrameworkCore.Diagnostics.Internal.RelationalCommandDiagnosticsLogger.CommandReaderExecutedAsync(IRelationalConnection connection, DbCommand command, DbContext context, Guid commandId, Guid connectionId, DbDataReader methodResult, DateTimeOffset startTime, TimeSpan duration, CommandSource commandSource, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(AsyncEnumerator enumerator, CancellationToken cancellationToken)
   at Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.NpgsqlExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
```

## Example Code 2:
```
services.AddEasyCaching(option =>
            {
                option.WithProtobuf();

                option.UseRedis(config =>
                {
                    config.DBConfig.AllowAdmin = true;
                    config.DBConfig.SyncTimeout = 10000;
                    config.DBConfig.AsyncTimeout = 10000;
                    config.DBConfig.Endpoints.Add(new EasyCaching.Core.Configurations.ServerEndPoint("redis", 6379));
                }, "DbRedis");
            });

            services.AddEFSecondLevelCache(options =>
            {
                options.UseEasyCachingCoreProvider("DbRedis", CacheExpirationMode.Absolute, TimeSpan.FromMinutes(30), isHybridCache: false).DisableLogging(true).UseCacheKeyPrefix("EF_");
            });
			
			services.AddDbContext<ConfigurationDbContext>((sp, o) =>
            {
                o.UseNpgsql(connectionString);
                o.AddInterceptors(sp.GetRequiredService<SecondLevelCacheInterceptor>());
            });
```

## Output Code 2:
```
    InvalidOperationException: Sequence contains no matching element
    System.Linq.ThrowHelper.ThrowNoMatchException()
    System.Linq.Enumerable.Single<TSource>(System.Collections.Generic.IEnumerable<TSource>, System.Func<TSource, bool>)
    EasyCaching.Redis.DefaultRedisCachingProvider.DefaultRedisCachingProvider(string, System.Collections.Generic.IEnumerable<EasyCaching.Redis.IRedisDatabaseProvider>, System.Collections.Generic.IEnumerable<EasyCaching.Core.Serialization.IEasyCachingSerializer>, EasyCaching.Redis.RedisOptions, EasyCaching.Redis.DistributedLock.RedisLockFactory, Microsoft.Extensions.Logging.ILoggerFactory)
    EasyCaching.Redis.RedisOptionsExtension.AddServices.AnonymousMethod__3_1(System.IServiceProvider)
    Autofac.Extensions.DependencyInjection.AutofacRegistration.Register.AnonymousMethod__0(Autofac.IComponentContext, System.Collections.Generic.IEnumerable<Autofac.Core.Parameter>)
    Autofac.Core.Activators.Delegate.DelegateActivator.ActivateInstance(Autofac.IComponentContext, System.Collections.Generic.IEnumerable<Autofac.Core.Parameter>)
    Autofac.Core.Activators.Delegate.DelegateActivator.ConfigurePipeline.AnonymousMethod__2_0(Autofac.Core.Resolving.Pipeline.ResolveRequestContext, System.Action<Autofac.Core.Resolving.Pipeline.ResolveRequestContext>)
    Autofac.Core.Resolving.Middleware.DisposalTrackingMiddleware.Execute(Autofac.Core.Resolving.Pipeline.ResolveRequestContext, System.Action<Autofac.Core.Resolving.Pipeline.ResolveRequestContext>)
    Autofac.Core.Resolving.Middleware.ActivatorErrorHandlingMiddleware.Execute(Autofac.Core.Resolving.Pipeline.ResolveRequestContext, System.Action<Autofac.Core.Resolving.Pipeline.ResolveRequestContext>)
```

**Comment by VahidN** [comment]
Try using the `MessagePack` instead. I have a sample about it [here](https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/blob/master/src/Tests/Issues/Issue123WithMessagePack/EFServiceProvider.cs#L64).

**Comment by c5racing** [comment]
> Try using the `MessagePack` instead. I have a sample about it [here](https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/blob/master/src/Tests/Issues/Issue123WithMessagePack/EFServiceProvider.cs#L64).

Using MessagePack exactly as your example, leaves me with the same error as Output 2 above:

`'An exception was thrown while activating EFCoreSecondLevelCacheInterceptor.SecondLevelCacheInterceptor -> EFCoreSecondLevelCacheInterceptor.DbCommandInterceptorProcessor -> EFCoreSecondLevelCacheInterceptor.EFEasyCachingCoreProvider.'`

One difference is I'm using the PostgreSQL EFCore Driver (Npgsql.EntityFrameworkCore.PostgreSQL v. 6.0.0) vs. SQL in your example.

I tried using the EasyCacheProvider 'InMemory', and it works without issue.

**Comment by VahidN** [comment]
`An exception was thrown while activating` usually means you are not feeding enough information to the `Autofac` to activate the required services. I don't use Autofac or any other DI providers with .NET/.NET Core anymore. If you are using it because it has `Scanning` features, I suggest using the [Scrutor](https://github.com/khellang/Scrutor) . It's an extension, not a replacement.

**Comment by c5racing** [comment]
> `An exception was thrown while activating` usually means you are not feeding enough information to the `Autofac` to activate the required services. I don't use Autofac or any other DI providers with .NET/.NET Core anymore. If you are using it because it has `Scanning` features, I suggest using the [Scrutor](https://github.com/khellang/Scrutor) . It's an extension, not a replacement.

I removed Autofac and using the built-in DI.  Using the same code as Output 2 above, here is the new stacktrace:

```
at System.Linq.ThrowHelper.ThrowNoMatchException()
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
   at EasyCaching.Redis.DefaultRedisCachingProvider..ctor(String name, IEnumerable`1 dbProviders, IEnumerable`1 serializers, RedisOptions options, RedisLockFactory factory, ILoggerFactory loggerFactory)
   at EasyCaching.Redis.RedisOptionsExtension.<AddServices>b__3_1(IServiceProvider x)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitIEnumerable(IEnumerableCallSite enumerableCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(Type serviceType)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at EFCoreSecondLevelCacheInterceptor.EFEasyCachingCoreProvider..ctor(IOptions`1 cacheSettings, IServiceProvider serviceProvider, IReaderWriterLockProvider readerWriterLockProvider, IEFDebugLogger logger) in D:\Prog\1398\EFCoreSecondLevelCacheInterceptor\src\EFCoreSecondLevelCacheInterceptor\EFEasyCachingCoreProvider.cs:line 50
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(Type serviceType)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Configuration.Api.Startup.<>c__DisplayClass4_0.<ConfigureServices>b__2(IServiceProvider sp, DbContextOptionsBuilder o) in C:\Users\brad\source\repos\SRM\src\Services\Configuration\Configuration.Api\Startup.cs:line 77
   at Microsoft.Extensions.DependencyInjection.EntityFrameworkServiceCollectionExtensions.CreateDbContextOptions[TContext](IServiceProvider applicationServiceProvider, Action`2 optionsAction)
   at Microsoft.Extensions.DependencyInjection.EntityFrameworkServiceCollectionExtensions.<>c__DisplayClass17_0`1.<AddCoreServices>b__0(IServiceProvider p)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass2_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Configuration.Application.Factories.LookupTableFactory.GetLookupTableService(TableName tableName) in C:\Users\brad\source\repos\SRM\src\Services\Configuration\Configuration.Application\Factories\LookupTableFactory.cs:line 23
   at Configuration.Application.Grpc.LookupTableGrpcServiceV1.Search(SearchLookupTableRequest request, ServerCallContext context) in C:\Users\brad\source\repos\SRM\src\Services\Configuration\Configuration.Application\Grpc\LookupTableGrpcServiceV1.cs:line 29
   at Grpc.Shared.Server.UnaryServerMethodInvoker`3.ResolvedInterceptorInvoker(TRequest resolvedRequest, ServerCallContext resolvedContext)
   at Grpc.Shared.Server.UnaryServerMethodInvoker`3.ResolvedInterceptorInvoker(TRequest resolvedRequest, ServerCallContext resolvedContext)
   at Application.Shared.Interceptors.ValidationInterceptor.UnaryServerHandler[TRequest,TResponse](TRequest request, ServerCallContext context, UnaryServerMethod`2 continuation) in C:\Users\brad\source\repos\SRM\src\BuildingBlocks\Application.Shared\Interceptors\ValidationInterceptor.cs:line 47

```

**Comment by c5racing** [comment]
This can be closed.  For anyone else experiencing the issue, you need to name the serializer and reference it:

```
            services.AddEasyCaching(options =>
            {
                options.WithJson("proto");

                options.UseRedis(config =>
                {
                    config.DBConfig.Endpoints.Add(new EasyCaching.Core.Configurations.ServerEndPoint("redis", 6379));
                    config.SerializerName = "proto";
                }, providerName);
            });
```

**Comment by Edgaras91** [comment]
> This can be closed. For anyone else experiencing the issue, you need to name the serializer and reference it:
> 
> ```
>             services.AddEasyCaching(options =>
>             {
>                 options.WithJson("proto");
> 
>                 options.UseRedis(config =>
>                 {
>                     config.DBConfig.Endpoints.Add(new EasyCaching.Core.Configurations.ServerEndPoint("redis", 6379));
>                     config.SerializerName = "proto";
>                 }, providerName);
>             });
> ```

You should add this on the "front page" of the guides. Without this, I can't get a basic Redis cache setup to work, only found info here.
