### ISSUE TITLE
Explicit Casting for Boolean Properties

### ISSUE THREAD

**Issue by yigityuksel** [VahidN/EFCoreSecondLevelCacheInterceptor#147]
Hi, 

While reading a boolean property, I am getting the following error. The database is MariaDB and the property is saved as TINYINT in Database.

`     "System.InvalidCastException",
        "Message": "Unable to cast object of type 'System.Boolean' to type 'System.UInt64'.",
`

## Environment

```
.NET (Core) SDK version:  3.1
Microsoft.EntityFrameworkCore version:  3.1.12
EFCoreSecondLevelCacheInterceptor version: 3.2.3
Database: (e.g. SQL Server, SQLite, etc.) MariaDB
Cache provider: (e.g. in-memory, redis, etc.) Inmemory
```

## If I override `Read()` function as follows, the error will not be thrown.

```
if (isBinary(i))
{
    _rowValues[i] = getSqlBytes(i);
}
else if (isBoolean(i))
{
    var k = _dbReader.GetBoolean(i);
    _rowValues[i] = Convert.ToUInt64(k);
}
else
{
    _rowValues[i] = _dbReader.GetValue(i);
}
```
### StackTrace
```

System.InvalidCastException: Unable to cast object of type 'System.Boolean' to type 'System.UInt64'.
   at System.Data.Common.DbDataReader.GetFieldValue[T](Int32 ordinal)
   at lambda_method(Closure , QueryContext , DbDataReader , ResultContext , Int32[] , ResultCoordinator )
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Controller.Get(ODataQueryOptions`1 queryOptions, CancellationToken cancellationToken) in Controller
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at InvokeAsync(HttpContext httpContext, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass5_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at AspNetCoreRateLimit.RateLimitMiddleware`1.Invoke(HttpContext context)
   at InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass5_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at OwaspHeaders.Core.SecureHeadersMiddleware.Invoke(HttpContext httpContext)
   at ErrorHandlingMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)

```

**Comment by VahidN** [comment]
What is the full stack trace of this exception?

**Comment by yigityuksel** [comment]
> What is the full stack trace of this exception?

I've added to the question.

**Comment by VahidN** [comment]
Sorry I am not going to fix this. It doesn't even hit this library according to your logs and probably it's a driver/provider issue.

**Comment by yigityuksel** [comment]
What do you mean it is not hitting the library? ProcessExecutedCommands method has DbDataReader that is used by EFDataReaderLoader. The error is thrown by there.  
[https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/blob/17503ea202f4f3f2b0abc482a2e4290c2194df77/src/EFCoreSecondLevelCacheInterceptor/DbCommandInterceptorProcessor.cs#L93](Code)

**Comment by VahidN** [comment]
> What do you mean it is not hitting the library?

There is no trace of this library in your posted stack trace. Not even a single line of it shows it's coming from this library or using it.

[There was a problem with TINYINT before](https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/issues/26) and it was fixed. Use a proper ef-core provider for your database.

**Comment by VahidN** [comment]
Try V 3.2.4. [It processes a boolean value as an int](https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/commit/ffc82e685f4c536a8a47235024f8e6acaac73185).

**Comment by VahidN** [comment]
Are you using the `Pomelo.EntityFrameworkCore.MySql ` provider? If yes, it has a [TreatTinyAsBoolean=true](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/search?q=TreatTinyAsBoolean) setting. Add it to your [connection string](https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/blob/master/src/Tests/Issues/Issue12MySQL/appsettings.json#L12). Also sometimes you will need to [write some converters](https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/blob/master/src/Tests/Issues/Issue12MySQL/DataLayer/ApplicationDbContext.cs#L35) to handle some missing types.
