### ISSUE TITLE
Using npgsql and nodatime with EFCoreSecondLevelCacheInterceptor leads to an exception.

### ISSUE THREAD

**Issue by jbaehr-phoenis** [VahidN/EFCoreSecondLevelCacheInterceptor#158]
# Summary of the issue

Using npgsql and nodatime with EFCoreSecondLevelCacheInterceptor leads to an exception.
It seems that the mapping is not resolved correctly.

## Environment

```
.NET (Core) SDK version: 6
Microsoft.EntityFrameworkCore version: 6.0.5
EFCoreSecondLevelCacheInterceptor version:  3.4.0
Database: Postgres
Cache provider: in-memory
```

## Output:

```

System.InvalidCastException: Unable to cast object of type 'NodaTime.Period' to type 'NodaTime.Duration'.
         at EFCoreSecondLevelCacheInterceptor.EFTableRowsDataReader.GetFieldValue[T](Int32 ordinal) in D:\Prog\1398\EFCoreSecondLevelCacheInterceptor\src\EFCoreSecondLevelCacheInterceptor\EFTableRowsDataReader.cs:line 539
         at lambda_method705(Closure , QueryContext , DbDataReader , ResultContext , SingleQueryResultCoordinator )
         at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
         at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
         at QFoxFramework.Components.QGrid`1.GetTableData(IQueryable`1 query, TableState state)
         at QFoxFramework.Components.QGrid`1.LoadData(TableState state)

```

**Comment by VahidN** [comment]
You should write a converter for it. [More info.](https://www.davepaquette.com/archive/2019/03/26/using-noda-time-with-ef-core.aspx)

**Comment by jbaehr-phoenis** [comment]
Would it be poossible to extend the EFTableRowsDataReader type to allow for custom mappings to be used in the `public override T GetFieldValue<T>(int ordinal)` method?
