### ISSUE TITLE
Unable to cast object of type 'System.Object[]' to type 'System.DateTimeOffset'.

### ISSUE THREAD

**Issue by kamalhamidi99** [VahidN/EFCoreSecondLevelCacheInterceptor#169]
# Summary of the issue
My entity contains a `DateTimeOffset` field which when trying to get it from the cache, throws an error, I test it several times but I could not fix the issue, please advise.
I tried to use `DateTimeOffsetFormatter.Instance` but the result didn't change. i also write a new `Formatter` just to see if it will be hit, but it didn't.

## Environment

```
.NET (Core) SDK version:  .net 5
Microsoft.EntityFrameworkCore version: 5.0.6
EFCoreSecondLevelCacheInterceptor version: 3.6.1
Database: SQL Server
Cache provider: in-memory
```

## Example code/Steps to reproduce:

```
            services.AddEasyCaching(option =>
            {
                option
                    .UseRedis(configuration)
                    .WithMessagePack(so =>
                    {
                        so.EnableCustomResolver = true;
                        so.CustomResolvers = CompositeResolver.Create(
                            new IMessagePackFormatter[]
                            {
                                DbNullFormatter.Instance, // This is necessary for the null values
                            },
                            new IFormatterResolver[]
                            {
                                NativeDateTimeResolver.Instance,
                                ContractlessStandardResolver.Instance,
                                StandardResolverAllowPrivate.Instance,
                                TypelessContractlessStandardResolver.Instance,
                            });
                    }, configuration["easycaching:redis:serializerName"]);
            });

    public class GetCustomerBusinessEmployeeDto
    {
        public Guid Id { get; set; }

        public Guid CustomerBusinessId { get; set; }

        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string SecondLastName { get; set; }

        public string Mobile { get; set; }
        public string MobileCountryCode { get; set; }
        public string MobileWithCode { get; set; }

        public string PersonalNumber { get; set; }

        public float PercentageOfShares { get; set; }

        public Guid? NationalityCountryId { get; set; }
        public Guid? ResidencyCountryId { get; set; }

        public string Email { get; set; }

        public DateTime BirthDate { get; set; }

        public DateTime DocumentExpirationDate { get; set; }

        public Guid? AddressId { get; set; }

        public CustomerBusinessEmployeeStatusEnum Status { get; set; }

        public Guid? CustomerId { get; set; }

        public DateTimeOffset CreatedDateTime { get; set; }

        public IList<CustomerBusinessEmployeeRoleDto> CustomerBusinessEmployeeRoles { get; set; }

        public class CustomerBusinessEmployeeRoleDto
        {
            public Guid Id { get; set; }
            public BusinessRoleEnum Role { get; set; }
            public bool IsDefault { get; set; }
        }
    }

```

## Output:

```
Exception message:
Unable to cast object of type 'System.Object[]' to type 'System.DateTimeOffset'.

Full Stack trace:
Unable to cast object of type 'System.Object[]' to type 'System.DateTimeOffset'.
  at EFCoreSecondLevelCacheInterceptor.EFTableRowsDataReader.GetFieldValue[T](Int32 ordinal) in D:\Prog\1398\EFCoreSecondLevelCacheInterceptor\src\EFCoreSecondLevelCacheInterceptor\EFTableRowsDataReader.cs:line 543
  at lambda_method2982(Closure , QueryContext , DbDataReader , ResultContext , SingleQueryResultCoordinator )
  at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
  at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
  at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
  at Be1B.Common.BLL.V2Services.Be1BDb.Addresses.GetAddress.GetAddressExecute.Dto(Guid id, CancellationToken cancellationToken) in D:\Project\_Rexuniversal\Be1Master\Be1B.Common.BLL\V2Services\Be1BDb\Addresses\GetAddress\GetAddressExecute.cs:line 26
  at Be1B.Antilo.Areas.Dashboard.Features.Team.TeamController.Details(Guid id, CancellationToken cancellationToken) in D:\Project\_Rexuniversal\Be1Master\Be1b.Antilo\Areas\Dashboard\Features\Team\TeamController.cs:line 107
  at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
  at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
  at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
  at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerAc…
```

**Comment by kamalhamidi99** [comment]
@VahidN

**Comment by VahidN** [comment]
There is no problem with SQL Server at all. [There are lots of test here](https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/tree/master/src/Tests/EFCoreSecondLevelCacheInterceptor.Tests) using the SQL Server with all kinds of date fields [with these settings](https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/blob/master/src/Tests/EFCoreSecondLevelCacheInterceptor.Tests/Settings/EFServiceProvider.cs#L169).

**Comment by kamalhamidi99** [comment]
I'm sorry in the environment I put `in-memory` which later I moved to Redis, so it's an issue with `easycaching.redis` but just to be sure, I change the configuration to in-memory and it didn't throw an error this time. 
Right now because I'm using several systems I had to use Redis and it's throwing an error just for `DateTimeOffset`, please advise? @VahidN

**Comment by kamalhamidi99** [comment]
instead of this package `EasyCaching.Serialization.MessagePack` i used `EasyCaching.Serialization.Json` and now it's working :) 

` services.AddEasyCaching(option =>
            {
                option
                    .UseRedis(configuration)
                    .WithJson(providerName1);
            });`
