### ISSUE TITLE
Error when using EFCoreSecondLevelCacheInterceptor

### ISSUE THREAD

**Issue by thomashoef** [VahidN/EFCoreSecondLevelCacheInterceptor#17]
# Summary of the issue

When adding the EF Cache Interceptor and using EF commands, I get this error:

Unable to resolve service for type 'EFCoreSecondLevelCacheInterceptor.IDbCommandInterceptorProcessor'

The DB has been configured and if I remove the "AddInterceptor" line all works.

What could be the reason for this error?

## Environment

```
.NET Core SDK version: 3.1
Microsoft.EntityFrameworkCore version: 3.1.3
EFCoreSecondLevelCacheInterceptor version:  1.3.4
```

## Example code/Steps to reproduce:

```
            var optionsBuilder = new DbContextOptionsBuilder<IdentityDbContext>();
            optionsBuilder.UseNpgsql(((IDbConfiguration) sp.GetService(typeof(IDbConfiguration))).ConnectionString);
            optionsBuilder.AddInterceptors(new SecondLevelCacheInterceptor());
```

## Output:

```
Exception message:
Full Stack trace:
 Unable to resolve service for type 'EFCoreSecondLevelCacheInterceptor.IDbCommandInterceptorProcessor'. This is often because no database provider has been configured for this DbContext. A provider can be configured by overriding the DbContext.OnConfiguring method or by using AddDbContext on the application service provider. If AddDbContext is used, then also ensure that your DbContext type accepts a DbContextOptions<TContext> object in its constructor and passes it to the base constructor for DbContext.
   at Microsoft.EntityFrameworkCore.Infrastructure.Internal.InfrastructureExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Infrastructure.AccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
   at EFCoreSecondLevelCacheInterceptor.SecondLevelCacheInterceptor.getProcessor(DbContext context)
   at EFCoreSecondLevelCacheInterceptor.SecondLevelCacheInterceptor.ReaderExecutingAsync(DbCommand command, CommandEventData eventData, InterceptionResult`1 result, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Diagnostics.RelationalLoggerExtensions.CommandReaderExecutingAsync(IDiagnosticsLogger`1 diagnostics, IRelationalConnection connection, DbCommand command, DbContext context, Guid commandId, Guid connectionId, DateTimeOffset startTime, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(DbContext _, Boolean result, CancellationToken cancellationToken)
   at Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.NpgsqlExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)


```

**Comment by VahidN** [comment]
- [Here is a working sample for Npgsql](https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/tree/master/src/Tests/Issues/Issue12PostgreSql).
- Probably you have not registered the [services.AddEFSecondLevelCache](https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/blob/master/src/Tests/Issues/Issue12PostgreSql/EFServiceProvider.cs#L58).

**Comment by thomashoef** [comment]
Hi Vahid, thanks for the reply. Actually I am using AddEFSecondLevelCache and registered the interceptor. I switched to inMemoryDb and still get the same error.

**Comment by VahidN** [comment]
This error means your db-context's instance has not access to the registered services of ` services.AddEFSecondLevelCache`. Are you using some special IoC container here other than the built-in one?

**Comment by pallotta** [comment]
I'm running into this same issue, but I believe my issue has something to do with me using Lamar IoC container instead of Microsoft built in.  Can you advise if there is a way to get this to work with Lamar?

**Comment by thomashoef** [comment]
@VahidN to your questions:
- using built-in .net core container
- addDbContext called 
- but yes, addDbContext ist called with new Context(options, param1, param2)

Should it not work if I first register a singleton with my new DBcontext and then call addDbContext<IMyDbContextInterface>?

**Comment by VahidN** [comment]
If you want to implement your `IDesignTimeDbContextFactory` [follow this sample](https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/blob/master/src/Tests/EFCoreSecondLevelCacheInterceptor.Tests.DataLayer/MsSqlContextFactory.cs#L37).

**Comment by pallotta** [comment]
Unfortunately, I'm still running into an issue.  I am calling:

           services.AddEFSecondLevelCache(options =>
            {
                options.UseMemoryCacheProvider();
                options.DisableLogging(true);
            });

followed by code which registers my DbContext and calls AddDbContext.

However I still get the same exception:

"Unable to resolve service for type 'EFCoreSecondLevelCacheInterceptor.IDbCommandInterceptorProcessor'. This is often because no database provider has been configured for this DbContext. A provider can be configured by overriding the DbContext.OnConfiguring method or by using AddDbContext on the application service provider. If AddDbContext is used, then also ensure that your DbContext type accepts a DbContextOptions<TContext> object in its constructor and passes it to the base constructor for DbContext."

   at Microsoft.EntityFrameworkCore.Infrastructure.Internal.InfrastructureExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Infrastructure.AccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
   at EFCoreSecondLevelCacheInterceptor.SecondLevelCacheInterceptor.getProcessor(DbContext context)
   at EFCoreSecondLevelCacheInterceptor.SecondLevelCacheInterceptor.NonQueryExecuting(DbCommand command, CommandEventData eventData, InterceptionResult`1 result)
   at Microsoft.EntityFrameworkCore.Diagnostics.RelationalLoggerExtensions.CommandNonQueryExecuting(IDiagnosticsLogger`1 diagnostics, IRelationalConnection connection, DbCommand command, DbContext context, Guid commandId, Guid connectionId, DateTimeOffset startTime)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQuery(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.ExecuteSqlRaw(DatabaseFacade databaseFacade, String sql, IEnumerable`1 parameters)
   at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.ExecuteSqlRaw(DatabaseFacade databaseFacade, String sql, Object[] parameters)
   at Mx.Data.Repositories.LoadLogRepository.FailIncompleteLoads() in C:\Users\JPallotta\Source\Repos\Mx-Latest\src\Mx.Data\Repositories\LoadLogRepository.cs:line 25
   at Mx.BusinessLogic.LoadLogFacade.FailIncompleteLoads() in C:\Users\JPallotta\Source\Repos\Mx-Latest\src\Mx.BusinessLogic\LoadLogFacade.cs:line 135
   at Mx.DataLoad.Server.DataLoadService.Start(String instanceName) in C:\Users\JPallotta\Source\Repos\Mx-Latest\src\Mx.DataLoad\Server\DataLoadService.cs:line 86
   at Mx.DataLoad.Server.App.Start(String instanceName) in C:\Users\JPallotta\Source\Repos\Mx-Latest\src\Mx.DataLoad\Server\App.cs:line 281
   at Mx.DataLoad.Server.Worker.<StartAsync>d__9.MoveNext() in C:\Users\JPallotta\Source\Repos\Mx-Latest\src\Mx.DataLoad\Server\Worker.cs:line 39
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>d__9.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.<RunAsync>d__4.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.<RunAsync>d__4.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at Mx.DataLoad.Worker.Service.Program.Main(String[] args) in C:\Users\JPallotta\Source\Repos\Mx-Latest\src\Mx.DataLoad.Worker.Service\Program.cs:line 20

**Comment by VahidN** [comment]
- I'm not using any third party IoC containers with .NET Core, because if you are using them to `Scan` services for you, it's better to use the https://github.com/khellang/Scrutor for this purpose. It's not a separate Ioc container. It's an add-on for the existing one.
- I added a new sample about using Lamar with ASP.NET Core [here](AspNetCoreSampleWithLamar). I just followed [its docs](https://jasperfx.github.io/lamar/documentation/ioc/aspnetcore/), added its package, added `UseLamar()` to `CreateHostBuilder` method of Program.cs file, and changed the signature of `public void ConfigureServices(...)` to `public void ConfigureContainer(ServiceRegistry services)` in `Startup.cs` and ... it works.

**Comment by pallotta** [comment]
Thanks for taking the time to look at it.  I think the difference might be that I'm using it in a .NET Core worker service and not a ASP.NET Core app.  I also followed their docs.  My Program.cs looks very similar to yours.  I also added UseLamar() to CreateHostBuilder method.  I don't think the UseStartup() and ConfigureContainer() methods are applicable to a worker service.  I could be missing something here.

**Comment by VahidN** [comment]
Added [WorkerServiceWithLamar](https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/tree/master/src/Tests/EFCoreSecondLevelCacheInterceptor.WorkerServiceWithLamar) sample.

**Comment by pallotta** [comment]
Thanks again very much for going to the trouble of creating a Lamar worker service example.  I see that I was missing the ConfigureContainer() call in my Program.cs, so I added that with my Lamar configuration being done within.  I noticed that you were still calling AddEFSecondLevelCache() and AdDbContext from within ConfigureServices, so I did the same.  So my code looks like your example, but for some reason I'm still getting the same exception.  I'm sure the problem is on my side.  Hopefully, I'll get it figured out.  You've obviously been able to get it to work with your example.  Thanks again!

**Comment by VahidN** [comment]
V 1.5.2 lets you to instantiate the db-context normally (using `new DbContext()`) as well.

**Comment by thomashoef** [comment]
Thanks Valid, this is great and works perfectly now!


Am 13.04.2020 um 09:38 schrieb Vahid Nasiri <notifications@github.com<mailto:notifications@github.com>>:



V 1.5.2 lets you to instantiate the db-context normally (using new DbContext()) as well.
