### ISSUE TITLE
Operation Canceled on Reads

### ISSUE THREAD

**Issue by stefannikolei** [VahidN/EFCoreSecondLevelCacheInterceptor#178]
# Summary of the issue
After the update our asp.net app stops working after some time.

I

It seems related to the latest changes:

Here is a stacktrace of the issue

System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at System.Threading.SemaphoreSlim.WaitUntilCountOrTimeoutAsync(TaskNode asyncWaiter, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at NeoSmart.AsyncLock.AsyncLock.InnerLock.ObtainLockAsync(CancellationToken ct)
   at EFCoreSecondLevelCacheInterceptor.SecondLevelCacheInterceptor.ReaderExecutingAsync(DbCommand command, CommandEventData eventData, InterceptionResult`1 result, CancellationToken cancellationToken) in F:\Prog\1398\EFCoreSecondLevelCacheInterceptor\src\EFCoreSecondLevelCacheInterceptor\SecondLevelCacheInterceptor.cs:line 196
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   
The table from which a query was tried is not even configured for Caching.

**Comment by VahidN** [comment]
There is nothing wrong here. It means your query has been canceled by the EF-Core. \
```C#
        public override async Task<InterceptionResult<DbDataReader>> ReaderExecutingAsync(
            DbCommand command,
            CommandEventData eventData,
            InterceptionResult<DbDataReader> result,
            CancellationToken cancellationToken = default)
```
`ReaderExecutingAsync` has a `cancellationToken` and it's set by the EF.

**Comment by stefannikolei** [comment]
@VahidN But why is there this line in the stacktrace? System.Threading.SemaphoreSlim.WaitUntilCountOrTimeoutAsync

**Comment by VahidN** [comment]
Because that line is using the value of the passed `CancellationToken`.

**Comment by stefannikolei** [comment]
@VahidN Thanks for publishing a new version. I think this fixes the problems i have seen
