### ISSUE TITLE
The expected type was 'NetTopologySuite.Geometries.Point' but the actual value was of type 'System.Byte[]'

### ISSUE THREAD

**Issue by davidkroukamp** [VahidN/EFCoreSecondLevelCacheInterceptor#188]
# Summary of the issue
I am using [Pomelo MySql / NetToplogySuite 7.0.0.-alpha1](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql) on top of my EF Core. I added `EfCoreSecondCachelevelInterceptor`, and now I get a `System.InvalidOperationException` I get it has to do with `NetTopologySuite.Geometries.Point` class, but how would I got about solving this?

## Environment

```
.NET (Core) SDK version: 7.X
Microsoft.EntityFrameworkCore version: 7.1.3
EFCoreSecondLevelCacheInterceptor version: 3.8.1
Database: MySql 8.0.31
Cache provider: Redis via EasyCaching 1.7.0
```

## Example Code:
```
builder.Services.AddDbContext<EvoFarmDatabaseContext>(
    dbContextOptions =>
    {
        dbContextOptions.UseMySql(builder.Configuration["ConnectionStrings:Default"],
                ServerVersion.AutoDetect(builder.Configuration["ConnectionStrings:Default"]),
                options =>
                {
                    options.MigrationsAssembly("Database");
                    options.EnableRetryOnFailure(10, TimeSpan.FromSeconds(30), null);
                    options.UseNetTopologySuite();
                })
            .AddInterceptors(builder.Services.BuildServiceProvider().GetRequiredService<SecondLevelCacheInterceptor>())
            .LogTo(Console.WriteLine, LogLevel.Information)
            .EnableSensitiveDataLogging()
            .EnableDetailedErrors()
            .UseLazyLoadingProxies();
    }
);

var providerName = "redis";
builder.Services.AddEFSecondLevelCache(options =>
    {
        options.UseEasyCachingCoreProvider(providerName, isHybridCache: false)
            .DisableLogging(true)
            .UseCacheKeyPrefix("ef_");
        options.CacheAllQueries(CacheExpirationMode.Absolute, TimeSpan.FromMinutes(30));
    }
);
builder.Services.AddEasyCaching(options => 
{
    options.UseRedis(builder.Configuration, providerName).WithJson(providerName);
});    
```

## Output:

```
Exception message:

System.InvalidOperationException: An error occurred while reading a database value for property 'Farm.GpsCoordinates'. The expected type was 'NetTopologySuite.Geometries.Point' but the actual value was of type 'System.Byte[]'.

Full Stack trace:

System.InvalidOperationException: An error occurred while reading a database value for property 'Farm.GpsCoordinates'. The expected type was 'NetTopologySuite.Geometries.Point' but the actual value was of type 'System.Byte[]'.
 ---> System.InvalidCastException: Unable to cast object of type 'EFCoreSecondLevelCacheInterceptor.EFTableRowsDataReader' to type 'MySqlConnector.MySqlDataReader'.
   at lambda_method468(Closure, DbDataReader, Int32[])
   at Microsoft.EntityFrameworkCore.Query.Internal.BufferedDataReader.BufferedDataRecord.ReadObject(DbDataReader reader, Int32 ordinal, ReaderColumn column)
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Query.Internal.BufferedDataReader.BufferedDataRecord.ReadObject(DbDataReader reader, Int32 ordinal, ReaderColumn column)
   at Microsoft.EntityFrameworkCore.Query.Internal.BufferedDataReader.BufferedDataRecord.ReadRow()
   at Microsoft.EntityFrameworkCore.Query.Internal.BufferedDataReader.BufferedDataRecord.Initialize(DbDataReader reader, IReadOnlyList`1 columns)
   at Microsoft.EntityFrameworkCore.Query.Internal.BufferedDataReader.Initialize(IReadOnlyList`1 columns)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.InitializeReader(Enumerator enumerator)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.<>c.<MoveNext>b__21_0(DbContext _, Enumerator enumerator)
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.<>c__DisplayClass28_0`2.<Execute>b__0(DbContext context, TState state)
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementation[TState,TResult](Func`3 operation, Func`3 verifySucceeded, TState state)
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.MoveNext()
   at System.Linq.Enumerable.TryGetSingle[TSource](IEnumerable`1 source, Boolean& found)
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at lambda_method475(Closure, QueryContext)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at EvoFarmApi.Controllers.ProfileController.Read(Int32 id) in D:\Work\EvoFarm\api\src\EvoFarmApi\Controllers\ProfileController.cs:line 61
   at lambda_method213(Closure, Object, Object[])
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
```

**Comment by VahidN** [comment]
Yes. [It's not supported](https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/issues/4).
