### ISSUE TITLE
Unable to cast object of type 'System.String' to type 'System.Byte[]'.

### ISSUE THREAD

**Issue by Keyblase** [VahidN/EFCoreSecondLevelCacheInterceptor#209]
# Summary of the issue
I tried some convertions for string to byte[] but not working, but I was thinking that I don't want this byte[] be cached, because today is useless, I researched some EFCoreSecondLevelCacheOptions functions in search of a CacheAllQueriesExceptContainingTypes but without All, is this possible?

## Environment

```
.NET (Core) SDK version: 7.0
Microsoft.EntityFrameworkCore version: 7.0.10
EFCoreSecondLevelCacheInterceptor version: 3.9.2
Database: SQL Server
Cache provider: Redis
```

## Example code/Steps to reproduce:
Make an cacheable whith an Model with byte[]. (obs: they save as string that byte of image - ok -, when I reaload and try to get this guy the exception occurs).

The Config 1:
```
var jss = new JsonSerializerSettings
{
    NullValueHandling = NullValueHandling.Ignore,
    ReferenceLoopHandling = ReferenceLoopHandling.Ignore,
    Converters = new List<JsonConverter> { new StringToByteArrayConverter() }
};

const string redisConfigurationKey = "redis";
ServiceCollection.AddSingleton(typeof(ICacheManagerConfiguration),
    new ConfigurationBuilder()
        .WithJsonSerializer(serializationSettings: jss, deserializationSettings: jss)
        .WithUpdateMode(CacheUpdateMode.Up)
        .WithRedisConfiguration(redisConfigurationKey, config => config
                .WithAllowAdmin()
                .WithDatabase(1)
                .WithEndpoint(redisConnection.Split(new char[1] { ':' })[0], 6379)
                .EnableKeyspaceEvents())
        .WithMaxRetries(100)
        .WithRetryTimeout(50)
        .WithRedisCacheHandle(redisConfigurationKey)
        .Build());
ServiceCollection.AddSingleton(typeof(ICacheManager<>), typeof(BaseCacheManager<>));

ServiceCollection.AddEFSecondLevelCache(options =>
                             options.UseCacheManagerCoreProvider(CacheExpirationMode.Sliding, TimeSpan.FromHours(24))
                                    .DisableLogging(true)
                                    .UseCacheKeyPrefix("OCTO__")
                                    
                                );
```
The config 2: 
```
services.AddDbContext<MasterDataContext>((serviceProvider, optionsBuilder) =>
                    optionsBuilder
                        .AddInterceptors(serviceProvider.GetRequiredService<SecondLevelCacheInterceptor>()));
```
Example property in Model:
```
[JsonConverter(typeof(StringToByteArrayConverter))]
 public byte[] FilLogo { get; set; }
```
The Converter:
```
internal class StringToByteArrayConverter : JsonConverter<byte[]>
{
    public override byte[] ReadJson(JsonReader reader, Type objectType, byte[] existingValue, bool hasExistingValue, JsonSerializer serializer)
    {
        if (reader.TokenType == JsonToken.String)
        {
            string base64String = (string)reader.Value;
            return Convert.FromBase64String(base64String);
        }

        throw new JsonSerializationException("Expected a string value for byte array conversion.");
    }

    public override void WriteJson(JsonWriter writer, byte[] value, JsonSerializer serializer)
    {
        string base64String = Convert.ToBase64String(value);
        writer.WriteValue(base64String);
    }
}
```
## Output:

```
Exception message: Unable to cast object of type 'System.String' to type 'System.Byte[]'.
Full Stack trace:
   at EFCoreSecondLevelCacheInterceptor.EFTableRowsDataReader.GetFieldValue[T](Int32 ordinal)
   at Microsoft.EntityFrameworkCore.Query.Internal.BufferedDataReader.BufferedDataRecord.ReadObject(DbDataReader reader, Int32 ordinal, ReaderColumn column)
   at Microsoft.EntityFrameworkCore.Query.Internal.BufferedDataReader.BufferedDataRecord.ReadRow()
   at Microsoft.EntityFrameworkCore.Query.Internal.BufferedDataReader.BufferedDataRecord.Initialize(DbDataReader reader, IReadOnlyList`1 columns)
   at Microsoft.EntityFrameworkCore.Query.Internal.BufferedDataReader.Initialize(IReadOnlyList`1 columns)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.InitializeReader(Enumerator enumerator)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.<>c.<MoveNext>b__21_0(DbContext _, Enumerator enumerator)
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.<>c__DisplayClass28_0`2.<Execute>b__0(DbContext context, TState state)
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementation[TState,TResult](Func`3 operation, Func`3 verifySucceeded, TState state)
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at MasterLibrary.Standard.DAO.Repository.FiliaisRepository.GetByUsuario(Int64 idUsuario, Nullable`1 matriz) in C:\GIT\octo-sgi\multidrogas\MasterSGi_Core\MasterLibrary.Standard\DAO\Repository\FiliaisRepository.cs:line 44
   at MasterLibrary.Standard.Service.Domain.FiliaisService.GetByUsuario(Int64 idUsuario, Nullable`1 matriz) in C:\GIT\octo-sgi\multidrogas\MasterSGi_Core\MasterLibrary.Standard\Service\Domain\FiliaisService.cs:line 18
   at WebApi.Data.Controllers.FiliaisController.GetFiliais(Nullable`1 matriz) in C:\GIT\octo-sgi\multidrogas\MasterSGi_Core\WebApi.Data\Controllers\FiliaisController.cs:line 40

```

**Comment by Keyblase** [comment]
> * No.
> * Have you tried using [the messagepack](https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/blob/master/src/Tests/Issues/Issue123WithMessagePack/EFServiceProvider.cs#L44)?

No.. this guy is for Easycache right? I'm using CacheManager.Core . But I'm actually reusing some configurations, as I'm migrating from a package called EntityFrameworkCore.Cacheable to yours due to compatibility with .Net 7, I'm going to switch to easy cache and return.

**Comment by Keyblase** [comment]
So, adding Easycache with messagepack it works! . The way that the 2 cacheManager save the byte is different. This resolves my problem, I just want to thanks for this awesome package and excellent feedback provided
