### ISSUE TITLE
Deserialization failing for List/array types of string

### ISSUE THREAD

**Issue by adnan-kamili** [VahidN/EFCoreSecondLevelCacheInterceptor#211]
# Summary of the issue
Deserialization failing for List/array types

## Environment
macOS
```
.NET (Core) SDK version: 7
Microsoft.EntityFrameworkCore version: 7
EFCoreSecondLevelCacheInterceptor version: 3.9.2
Database: Postgres
Cache provider: redis
```

## Example code/Steps to reproduce:

```
                if (Configuration.Get<AppOptions>().Redis.EnableDatabaseCaching)
                {
                    Log.Logger.Information("Enabling database Redis caching...");

                    // const string memoryProviderName = "memory";
                    const string redisProviderName = "redis";
                    // const string hybridProviderName = "hybrid";

                    services.AddEFSecondLevelCache(options =>
                    {
                        options.UseEasyCachingCoreProvider(redisProviderName, CacheExpirationMode.Absolute, TimeSpan.FromMinutes(1), isHybridCache: false).DisableLogging(false).UseCacheKeyPrefix("EF_");
                    });

                    services.AddEasyCaching(option =>
                    {
                   
                        option.UseRedis(config =>
                        {
                            config.DBConfig.AllowAdmin = true;
                            config.DBConfig.Configuration = Configuration.Get<AppOptions>().Redis.Url;
                            config.EnableLogging = false;
                            config.SerializerName = "message-pack";
                            config.DBConfig.ConnectionTimeout = 10000;
                        }, redisProviderName)
                        .WithMessagePack(config =>
                        {
                            config.EnableCustomResolver = true;
                            config.CustomResolvers = CompositeResolver.Create(
                            new IMessagePackFormatter[]
                            {
                                DBNullFormatter.Instance, // This is necessary for the null values
                            },
                            new IFormatterResolver[]
                            {
                                NativeDateTimeResolver.Instance,
                                ContractlessStandardResolver.Instance,
                                StandardResolverAllowPrivate.Instance,
                            });
                        },"message-pack");
                        
                    });
                }
```

## Output:

```
[13:05:29 ERR] [0HMUESAFU7VSV:00000001] - Constructor on type 'System.Collections.Generic.List`1[[System.String, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]' not found.
System.MissingMethodException: Constructor on type 'System.Collections.Generic.List`1[[System.String, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]' not found.
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture)
   at EFCoreSecondLevelCacheInterceptor.EFTableRowsDataReader.GetFieldValue[T](Int32 ordinal) in D:\a\EFCoreSecondLevelCacheInterceptor\EFCoreSecondLevelCacheInterceptor\src\EFCoreSecondLevelCacheInterceptor\EFTableRowsDataReader.cs:line 544
   at lambda_method599(Closure, QueryContext, DbDataReader, ResultContext, SingleQueryResultCoordinator)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
   at CryptlexWebApi.Controllers.ProductsController.Get(String id) in /Users/adnan/Projects/CryptlexWebApi/Controllers/ProductsController.cs:line 91
   at lambda_method577(Closure, Object)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
```

**Comment by adnan-kamili** [comment]
Thanks for the quick fix. I updated to 3.9.3 but still getting the same error:

```[20:08:05 ERR] [0HMUF3QKRG657:00000002] - Constructor on type 'System.Collections.Generic.List`1[[System.String, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]' not found.
System.MissingMethodException: Constructor on type 'System.Collections.Generic.List`1[[System.String, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]' not found.
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture)
   at EFCoreSecondLevelCacheInterceptor.EFTableRowsDataReader.GetFieldValue[T](Int32 ordinal) in D:\a\EFCoreSecondLevelCacheInterceptor\EFCoreSecondLevelCacheInterceptor\src\EFCoreSecondLevelCacheInterceptor\EFTableRowsDataReader.cs:line 544
   at lambda_method440(Closure, QueryContext, DbDataReader, ResultContext, SingleQueryResultCoordinator)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
   at CryptlexWebApi.Controllers.ProductsController.Get(String id) in /Users/adnan/Projects/CryptlexWebApi/Controllers/ProductsController.cs:line 91
   at lambda_method418(Closure, Object)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
```
