### ISSUE TITLE
Crash when calling `context.Database.EnsureCreatedAsync()`

### ISSUE THREAD

**Issue by Anduin2017** [VahidN/EFCoreSecondLevelCacheInterceptor#222]
After upgrading from `4.0.0` to `4.1.0`, I found I couldn't run `context.Database.EnsureCreatedAsync()`.

To repro, I created a new .NET 7 project with latest EFCoreSecondLevelCacheInterceptor and Entity framework:

```xml
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="7.0.14" />
    <PackageReference Include="EFCoreSecondLevelCacheInterceptor" Version="4.1.0" />
```

```csharp
        [TestMethod]
        public async Task TestEnsureCreated()
        {
            var sampleDb = new ServiceCollection()
                .AddLogging(l => l.AddConsole())
                .AddDbContext<SampleDbContext>((serviceProvider, optionsBuilder) =>
                {
                    optionsBuilder
                        .UseSqlite(connectionString: "DataSource=app.db")
                        .AddInterceptors(serviceProvider.GetRequiredService<SecondLevelCacheInterceptor>());
                })
                .AddEFSecondLevelCache(o => { })
                .BuildServiceProvider().GetRequiredService<SampleDbContext>();
            await sampleDb.Database.EnsureCreatedAsync();
        }


    public class SampleDbContext : DbContext
    {
        public SampleDbContext(DbContextOptions<SampleDbContext> options) : base(options)
        {
        }
    }
```

When I run that test, I got an exception:

```log
Test method Aiursoft.DbTools.Tests.ProgramExtendsTests.TestEnsureCreated threw exception: 
System.ArgumentNullException: Value cannot be null. (Parameter 'context')
    at EFCoreSecondLevelCacheInterceptor.DbCommandInterceptorProcessor.ProcessExecutingCommands[T](DbCommand command, DbContext context, T result) in D:\a\EFCoreSecondLevelCacheInterceptor\EFCoreSecondLevelCacheInterceptor\src\EFCoreSecondLevelCacheInterceptor\DbCommandInterceptorProcessor.cs:line 206
   at EFCoreSecondLevelCacheInterceptor.SecondLevelCacheInterceptor.ScalarExecuting(DbCommand command, CommandEventData eventData, InterceptionResult`1 result) in D:\a\EFCoreSecondLevelCacheInterceptor\EFCoreSecondLevelCacheInterceptor\src\EFCoreSecondLevelCacheInterceptor\SecondLevelCacheInterceptor.cs:line 207
   at Microsoft.EntityFrameworkCore.Diagnostics.Internal.RelationalCommandDiagnosticsLogger.CommandScalarExecuting(IRelationalConnection connection, DbCommand command, DbContext context, Guid commandId, Guid connectionId, DateTimeOffset startTime, CommandSource commandSource)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteScalar(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Sqlite.Storage.Internal.SqliteDatabaseCreator.HasTables()
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabaseCreator.HasTablesAsync(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabaseCreator.EnsureCreatedAsync(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabaseCreator.EnsureCreatedAsync(CancellationToken cancellationToken)
   at Aiursoft.DbTools.Tests.ProgramExtendsTests.TestEnsureCreated() in C:\Users\AnduinXue\Source\Repos\Aiursoft\DbTools\tests\Aiursoft.DbTools.Tests\ProgramExtendTests.cs:line 48




fail: Microsoft.EntityFrameworkCore.Database.Command[20102]
      Failed executing DbCommand (2ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT COUNT(*) FROM "sqlite_master" WHERE "type" = 'table' AND "rootpage" IS NOT NULL;
```

Now if I downgrade it:

```xml
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="7.0.14" />
    <PackageReference Include="EFCoreSecondLevelCacheInterceptor" Version="4.0.0" />
```

Then everything works just fine!

```log
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (5ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT COUNT(*) FROM "sqlite_master" WHERE "type" = 'table' AND "rootpage" IS NOT NULL;
```

I tried that no matter what cache provider or dbcontext, it can always reproduce.

**Comment by Anduin2017** [comment]
Thank you @VahidN !!! It solved!
