### ISSUE TITLE
How should I do unit testing？

### ISSUE THREAD

**Issue by ldqk** [VahidN/EFCoreSecondLevelCacheInterceptor#234]
# Summary of the issue
How should I do unit testing with extension method call of Cacheable？

## Environment

```
.NET (Core) SDK version: 8.0
Microsoft.EntityFrameworkCore version: 8.0
EFCoreSecondLevelCacheInterceptor version: 4.2.3
Database: SQL Server
Cache provider: MockQueryable.Moq
```

## Example code/Steps to reproduce:
I have a simple Business Class:
```csharp
public class MenuService(IRepository<Menus> menuRepository) : IMenuService
{
    public List<Menu> GetList()
    {
        var list = menuRepository.AsQueryable(false).OrderBy(a => a.Name).Cacheable().ToList();
        return list;
    }
}
```
My Unit Test Code:
```csharp
public class MenuServiceTest
{
    private readonly Mock<IRepository<Menu>> _menuRepoMock = new Mock<IRepository<Menu>>();

    public MenuService MenuService => new MenuService(_menuRepoMock.Object);

    [Fact]
    public void Can_GetList()
    {
        // arrange
        var queryable = new List<Menu>(){new Menu()}.BuildMock();
        _menuRepoMock.Setup(r => r.AsQueryable(false)).Returns(queryable);

        // act
        var list = MenuService.GetList();

        // assert
        Assert.True(list.Count > 0);
    }
}
```
run this unit test throw this exception: System.NotSupportedException
`Cacheable` method is designed only for relational EF Core queries.

## Output:

```
System.NotSupportedException
`Cacheable` method is designed only for relational EF Core queries.
   at EFCoreSecondLevelCacheInterceptor.EFCachedQueryExtensions.sanityCheck[TType](IQueryable`1 query) in D:\a\EFCoreSecondLevelCacheInterceptor\EFCoreSecondLevelCacheInterceptor\src\EFCoreSecondLevelCacheInterceptor\EFCachedQueryExtensions.cs:line 264
   at EFCoreSecondLevelCacheInterceptor.EFCachedQueryExtensions.Cacheable[TType](IQueryable`1 query) in D:\a\EFCoreSecondLevelCacheInterceptor\EFCoreSecondLevelCacheInterceptor\src\EFCoreSecondLevelCacheInterceptor\EFCachedQueryExtensions.cs:line 119
   at Assure.Confirmation.Application.Services.AnswerService.GetList() in C:\Works\Assure.Confirmation\services\Assure.Confirmation.Application\Services\AnswerService.cs:line 8
   at Assure.Confirmation.Application.Test.Services.AnswerServiceTest.Can_GetList() in C:\Works\Assure.Confirmation\services\Assure.Confirmation.Application.Test\Services\AnswerServiceTest.cs:line 31
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)

```

**Comment by VahidN** [comment]
Just don't use it and get lost.
