### ISSUE TITLE
Serialization exception when using the library

### ISSUE THREAD

**Issue by zorgoz** [VahidN/EFCoreSecondLevelCacheInterceptor#259]
related: https://stackoverflow.com/questions/79184028/efsecondlevelcache-serialization-issue

# Summary of the issue
I am trying to add second-level caching to my dbcontext. I am using PostgreSQL with quite a lot of JSON fields. Some have converters of their own. And they are added to the mix and used by EF and npgsql as expexted. Adding caching however introduces an excception related to one of the types that do have converter - hinting to the library trying to do some deserialization without taking them into consideration.

The same code works as expected when `options.AddInterceptors()` is removed.

## Environment

```
.NET (Core) SDK version: 9.0.100-rc.2.24474.11
Microsoft.EntityFrameworkCore version: 8.0.10
EFCoreSecondLevelCacheInterceptor version: 4.8.7
Database: (e.g. SQL Server, SQLite, etc.) PostgreSQL
Cache provider: (e.g. in-memory, redis, etc.) in-memory
```

## Example code:

```
services.AddEFSecondLevelCache(options =>
            options.UseMemoryCacheProvider()
                .CacheAllQueries(CacheExpirationMode.Absolute, TimeSpan.FromMinutes(5))
                .ConfigureLogging(true)
                .UseCacheKeyPrefix("EF_")
                .UseJsonSerializerOptions(CustomJsonSerializationOptions.ContractOptions)
        );

var dataSourceBuilder = new NpgsqlDataSourceBuilder(connectionStringSupplier(builder.Configuration));
dataSourceBuilder
    .ConfigureJsonOptions(CustomJsonSerializationOptions.ContractOptions)
    .EnableDynamicJson()
    .UseNodaTime()
    ;
....
var dataSource = dataSourceBuilder.Build();

builder.Services.AddDbContextFactory<T>((serviceProvider, options) =>
{
    options
        .UseExceptionProcessor()
        .UseNpgsql(dataSource, o => o.ConfigureOptions(migrationHistoryTableName, migrationAssembly))
        ;

    options.AddInterceptors(serviceProvider.GetRequiredService<SecondLevelCacheInterceptor>());
});

.....
public static JsonSerializerOptions ContractOptions { get; } = (new JsonSerializerOptions
{
    Converters = {
            new JsonStringEnumConverter(),
            new UlidJsonConverter(),
            new ValidatorCollectionConverter(),
            new PropertyCollectionConverter(),
            new PolymorphicJsonConverter<IValidationAttributeBase>(),
            new PolymorphicJsonConverter<GenericPropertyDescriptor>(),
        },
}).ConfigureForNodaTime(DateTimeZoneProviders.Tzdb);

```

## Output:
Note above: **PropertyCollectionConverter** that is exactly for the type the exception is about.
```
Exception message:
The collection type '....PropertyCollection' is abstract, an interface, or is read only, and could not be instantiated and populated. Path: $ | LineNumber: 0 | BytePositionInLine: 1.
Full Stack trace:
   at System.Text.Json.ThrowHelper.ThrowNotSupportedException(ReadStack& state, Utf8JsonReader& reader, NotSupportedException ex)
   at System.Text.Json.Serialization.Converters.IEnumerableOfTConverter`2.CreateCollection(Utf8JsonReader& reader, ReadStack& state, JsonSerializerOptions options)
   at System.Text.Json.Serialization.JsonCollectionConverter`2.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, TCollection& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo`1 jsonTypeInfo, Nullable`1 actualByteCount)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo`1 jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
   at EFCoreSecondLevelCacheInterceptor.EFTableRowsDataReader.GetFieldValue[T](Int32 ordinal)
   at Microsoft.EntityFrameworkCore.Query.Internal.BufferedDataReader.BufferedDataRecord.ReadObject(DbDataReader reader, Int32 ordinal, ReaderColumn column)
   at Microsoft.EntityFrameworkCore.Query.Internal.BufferedDataReader.BufferedDataRecord.ReadRow()
   at Microsoft.EntityFrameworkCore.Query.Internal.BufferedDataReader.BufferedDataRecord.<InitializeAsync>d__90.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.BufferedDataReader.<InitializeAsync>d__27.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.BufferedDataReader.<InitializeAsync>d__27.MoveNext()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.<ExecuteReaderAsync>d__18.MoveNext()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.<ExecuteReaderAsync>d__18.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.SplitQueryingEnumerable`1.AsyncEnumerator.<InitializeReaderAsync>d__22.MoveNext()
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.<>c__DisplayClass30_0`2.<<ExecuteAsync>b__0>d.MoveNext()
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.<ExecuteImplementationAsync>d__31`2.MoveNext()
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.<ExecuteImplementationAsync>d__31`2.MoveNext()
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.<ExecuteAsync>d__30`2.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.SplitQueryingEnumerable`1.AsyncEnumerator.<MoveNextAsync>d__21.MoveNext()
   at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult()
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.<SingleOrDefaultAsync>d__15`1.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.<SingleOrDefaultAsync>d__15`1.MoveNext()
   at WorkflowApi.Controllers.DashboardController.<GetCanStartWorkflows>d__3.MoveNext() in ...\DashboardController.cs:line 54
```

**Comment by VahidN** [comment]
[Use the new version](https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/commit/0c55f749aad24016c0f6ec5e99b2b6dfcb226cf9)
