### ISSUE TITLE
System.InvalidCastException on MySQL Pomelo

### ISSUE THREAD

**Issue by adisazhar123** [VahidN/EFCoreSecondLevelCacheInterceptor#26]
# Summary of the issue
Using EF Core Pomelo Mysql and Redis. Configured with Cachemanagercore as recommended in the documentstion.
Error:
```
System.InvalidCastException: Unable to cast object of type 'System.Int32' to type 'System.Boolean'.
   at EFCoreSecondLevelCacheInterceptor.EFTableRowsDataReader.GetBoolean(Int32 ordinal)
   at lambda_method(Closure , QueryContext , DbDataReader , ResultContext , Int32[] , ResultCoordinator )
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()

```

## Environment

```
.NET Core SDK version: 3.1
Microsoft.EntityFrameworkCore version: 3.1
EFCoreSecondLevelCacheInterceptor version:  1.5.4
```

## Example code/Steps to reproduce:

Can't post the code sample as it's confidential. But the models in the repository used have properties with datatypes Guid, string, boolean, Datetime, and int.

## Output:

```
Exception message:
Full Stack trace:
System.InvalidCastException: Unable to cast object of type 'System.Int32' to type 'System.Boolean'.
   at EFCoreSecondLevelCacheInterceptor.EFTableRowsDataReader.GetBoolean(Int32 ordinal)
   at lambda_method(Closure , QueryContext , DbDataReader , ResultContext , Int32[] , ResultCoordinator )
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at MyOrg.Application.Service.UserQuizRooms.UserQuizRoomsService.GetHistoryAsync(Guid userId) in /home/adis/projects/dotnet/MyApp/src/Services/Quiz/MyApp.Application/Service/UserQuizRooms/UserQuizRoomsService.cs:line 329
   at MyOrg.Controllers.UserQuizRoomsController.GetHistoryAsync() in /home/adis/projects/dotnet/MyApp/src/Services/Quiz/MyApp.Presentation/Controllers/UserQuizRoomsController.cs:line 171
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

```

**Comment by adisazhar123** [comment]
@VahidN

**Comment by VahidN** [comment]
Improved it via #https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/commit/14141f498c45482e1ab29e5a00c7ac3938621181#diff-68f3eac7cd152a1e597d0d4cc534836aR146
