### ISSUE TITLE
Cannot have 2 or more OwnsOnes of the same type on a model.

### ISSUE THREAD

**Issue by AprilHickson** [VahidN/EFCoreSecondLevelCacheInterceptor#42]
# Summary of the issue

Cannot have 2 or more `OwnsOne`s of the same type on a model.

A potential fix for our issue could be inside of `EFSqlCommandsProcessor.GetAllTableNames` to change the line `tableNames.Add(entityType.ClrType, entityType.GetTableName());` to use a `TryAdd()` instead of `Add()`

## Environment

```
.NET Core SDK version: 3.1
Microsoft.EntityFrameworkCore version: 3.1.6
EFCoreSecondLevelCacheInterceptor version: 1.8.0
```

## Example code/Steps to reproduce:

```
protected override void OnModelCreating(ModelBuilder builder)
{
    builder.Entity<EngineVersion>().OwnsOne(p => p.Commercial);
    builder.Entity<EngineVersion>().OwnsOne(p => p.Retail);
}
```

```
public class EngineVersion
{
    public int Id { get; set; }

    public EngineProductVersion Commercial { get; set; }
    public EngineProductVersion Retail { get; set; }
}

public class EngineProductVersion
{
    public int Major { get; set; }
    public int Minor { get; set; }
    public int Revision { get; set; }
    public int Patch { get; set; }

    public override string ToString()
        =>  $"{Major}.{Minor}.{Revision}.{Patch}";
}
```

## Output:

```
System.ArgumentException: An item with the same key has already been added. Key: Application.Core.Models.EngineProductVersion
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at EFCoreSecondLevelCacheInterceptor.EFSqlCommandsProcessor.<>c__DisplayClass3_0.<GetAllTableNames>b__1()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at EFCoreSecondLevelCacheInterceptor.EFSqlCommandsProcessor.GetAllTableNames(DbContext context)
   at EFCoreSecondLevelCacheInterceptor.DbCommandInterceptorProcessor.ProcessExecutingCommands[T](DbCommand command, DbContext context, T result)
   at EFCoreSecondLevelCacheInterceptor.SecondLevelCacheInterceptor.NonQueryExecuting(DbCommand command, CommandEventData eventData, InterceptionResult`1 result)
   at Microsoft.EntityFrameworkCore.Diagnostics.RelationalLoggerExtensions.CommandNonQueryExecuting(IDiagnosticsLogger`1 diagnostics, IRelationalConnection connection, DbCommand command, DbContext context, Guid commandId, Guid connectionId, DateTimeOffset startTime)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQuery(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerDatabaseCreator.<>c__DisplayClass18_0.<Exists>b__0(DateTime giveUp)
   at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.<>c__DisplayClass12_0`2.<Execute>b__0(DbContext c, TState s)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.Execute[TState,TResult](IExecutionStrategy strategy, TState state, Func`2 operation, Func`2 verifySucceeded)
   at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.Execute[TState,TResult](IExecutionStrategy strategy, TState state, Func`2 operation)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerDatabaseCreator.Exists(Boolean retryOnNotExists)   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerDatabaseCreator.Exists()
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabaseCreator.CanConnect()
   at Microsoft.EntityFrameworkCore.Infrastructure.DatabaseFacade.CanConnect()
   at Application.API.Program.WaitForDatabaseToExistAndMigrate(IServiceProvider services) in C:\Projects\Application\Master\src\Application.API\Program.cs:line 106
   at Application.API.Program.Main(String[] args) in C:\Projects\Application\Master\src\Application.API\Program.cs:line 67
```

**Comment by VahidN** [comment]
Thanks for reporting it. Fixed it via#https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/commit/c37cb4e51e16ae551dc2258881cb26adb566e624 .
