### ISSUE TITLE
When using CacheManager for redis cache, TimeSpan cache is not converted properly

### ISSUE THREAD

**Issue by jasonycw** [VahidN/EFCoreSecondLevelCacheInterceptor#44]
# Summary of the issue
I recently migrating our service from `EFSecondLevelCache.Core` to `EFCoreSecondLevelCacheInterceptor`.
It was caching the `TimeSpan` properly before, but after change to use `EFCoreSecondLevelCacheInterceptor`, without changing the `CacheManager` implementation and JsonSerializer, when query from redis cache, it throws 
> System.InvalidCastException: Unable to cast object of type 'System.String' to type 'System.TimeSpan'.

I checked the redis record and saw that the JSON is something like 
``` JSON
{
	"TableRows": {
		"Rows": [{
				"Values": [1608627, 1608627, "18:00:00", "08:30:00", 1608627, "18:00:00", "08:30:00", 1608627, "00:00:00", "00:00:00", 1608627, "00:00:00", "00:00:00", 1608627, "18:00:00", "08:30:00", 1608627, "18:00:00", "08:30:00", 1608627, "18:00:00", "08:30:00", 1608627, 1608526, "2020-07-31T00:00:00", "Hari Raya Haji", "00:00:00", "00:00:00"],
				"Depth": 0,
				"FieldCount": 28
			}, {
				"Values": [1608627, 1608627, "18:00:00", "08:30:00", 1608627, "18:00:00", "08:30:00", 1608627, "00:00:00", "00:00:00", 1608627, "00:00:00", "00:00:00", 1608627, "18:00:00", "08:30:00", 1608627, "18:00:00", "08:30:00", 1608627, "18:00:00", "08:30:00", 1608627, 1608526, "2020-08-09T00:00:00", "National Day", "00:00:00", "00:00:00"],
				"Depth": 0,
				"FieldCount": 28
			}, {
				"Values": [1608627, 1608627, "18:00:00", "08:30:00", 1608627, "18:00:00", "08:30:00", 1608627, "00:00:00", "00:00:00", 1608627, "00:00:00", "00:00:00", 1608627, "18:00:00", "08:30:00", 1608627, "18:00:00", "08:30:00", 1608627, "18:00:00", "08:30:00", 1608627, 1608526, "2020-08-10T00:00:00", "The day after National Day", "00:00:00", "00:00:00"],
				"Depth": 0,
				"FieldCount": 28
			}, {
				"Values": [1608627, 1608627, "18:00:00", "08:30:00", 1608627, "18:00:00", "08:30:00", 1608627, "00:00:00", "00:00:00", 1608627, "00:00:00", "00:00:00", 1608627, "18:00:00", "08:30:00", 1608627, "18:00:00", "08:30:00", 1608627, "18:00:00", "08:30:00", 1608627, 1608526, "2020-11-14T00:00:00", "Deepavali", "00:00:00", "00:00:00"],
				"Depth": 0,
				"FieldCount": 28
			}, {
				"Values": [1608627, 1608627, "18:00:00", "08:30:00", 1608627, "18:00:00", "08:30:00", 1608627, "00:00:00", "00:00:00", 1608627, "00:00:00", "00:00:00", 1608627, "18:00:00", "08:30:00", 1608627, "18:00:00", "08:30:00", 1608627, "18:00:00", "08:30:00", 1608627, 1608526, "2020-12-25T00:00:00", "Christmas Day", "00:00:00", "00:00:00"],
				"Depth": 0,
				"FieldCount": 28
			}
		],
		"ColumnsInfo": {
			"0": {
				"Ordinal": 0,
				"Name": "CentreId",
				"DbTypeName": "int",
				"TypeName": "System.Int32"
			},
			"1": {
				"Ordinal": 1,
				"Name": "CentreId0",
				"DbTypeName": "int",
				"TypeName": "System.Int32"
			},
			"2": {
				"Ordinal": 2,
				"Name": "FridayCloseTime",
				"DbTypeName": "time",
				"TypeName": "System.TimeSpan"
			},
			"3": {
				"Ordinal": 3,
				"Name": "FridayOpenTime",
				"DbTypeName": "time",
				"TypeName": "System.TimeSpan"
			},
			"4": {
				"Ordinal": 4,
				"Name": "CentreId1",
				"DbTypeName": "int",
				"TypeName": "System.Int32"
			},
			"5": {
				"Ordinal": 5,
				"Name": "MondayCloseTime",
				"DbTypeName": "time",
				"TypeName": "System.TimeSpan"
			},
			"6": {
				"Ordinal": 6,
				"Name": "MondayOpenTime",
				"DbTypeName": "time",
				"TypeName": "System.TimeSpan"
			},
			"7": {
				"Ordinal": 7,
				"Name": "CentreId2",
				"DbTypeName": "int",
				"TypeName": "System.Int32"
			},
			"8": {
				"Ordinal": 8,
				"Name": "SaturdayCloseTime",
				"DbTypeName": "time",
				"TypeName": "System.TimeSpan"
			},
			"9": {
				"Ordinal": 9,
				"Name": "SaturdayOpenTime",
				"DbTypeName": "time",
				"TypeName": "System.TimeSpan"
			},
			"10": {
				"Ordinal": 10,
				"Name": "CentreId3",
				"DbTypeName": "int",
				"TypeName": "System.Int32"
			},
			"11": {
				"Ordinal": 11,
				"Name": "SundayCloseTime",
				"DbTypeName": "time",
				"TypeName": "System.TimeSpan"
			},
			"12": {
				"Ordinal": 12,
				"Name": "SundayOpenTime",
				"DbTypeName": "time",
				"TypeName": "System.TimeSpan"
			},
			"13": {
				"Ordinal": 13,
				"Name": "CentreId4",
				"DbTypeName": "int",
				"TypeName": "System.Int32"
			},
			"14": {
				"Ordinal": 14,
				"Name": "ThursdayCloseTime",
				"DbTypeName": "time",
				"TypeName": "System.TimeSpan"
			},
			"15": {
				"Ordinal": 15,
				"Name": "ThursdayOpenTime",
				"DbTypeName": "time",
				"TypeName": "System.TimeSpan"
			},
			"16": {
				"Ordinal": 16,
				"Name": "CentreId5",
				"DbTypeName": "int",
				"TypeName": "System.Int32"
			},
			"17": {
				"Ordinal": 17,
				"Name": "TuesdayCloseTime",
				"DbTypeName": "time",
				"TypeName": "System.TimeSpan"
			},
			"18": {
				"Ordinal": 18,
				"Name": "TuesdayOpenTime",
				"DbTypeName": "time",
				"TypeName": "System.TimeSpan"
			},
			"19": {
				"Ordinal": 19,
				"Name": "CentreId6",
				"DbTypeName": "int",
				"TypeName": "System.Int32"
			},
			"20": {
				"Ordinal": 20,
				"Name": "WednesdayCloseTime",
				"DbTypeName": "time",
				"TypeName": "System.TimeSpan"
			},
			"21": {
				"Ordinal": 21,
				"Name": "WednesdayOpenTime",
				"DbTypeName": "time",
				"TypeName": "System.TimeSpan"
			},
			"22": {
				"Ordinal": 22,
				"Name": "CentreId",
				"DbTypeName": "int",
				"TypeName": "System.Int32"
			},
			"23": {
				"Ordinal": 23,
				"Name": "BuildingId",
				"DbTypeName": "int",
				"TypeName": "System.Int32"
			},
			"24": {
				"Ordinal": 24,
				"Name": "Date",
				"DbTypeName": "date",
				"TypeName": "System.DateTime"
			},
			"25": {
				"Ordinal": 25,
				"Name": "HolidayName",
				"DbTypeName": "nvarchar",
				"TypeName": "System.String"
			},
			"26": {
				"Ordinal": 26,
				"Name": "CloseTime",
				"DbTypeName": "time",
				"TypeName": "System.TimeSpan"
			},
			"27": {
				"Ordinal": 27,
				"Name": "OpenTime",
				"DbTypeName": "time",
				"TypeName": "System.TimeSpan"
			}
		},
		"FieldCount": 28,
		"TableName": "db55708c-7d88-4feb-86fe-aacab1421ae2",
		"HasRows": true,
		"RecordsAffected": -1,
		"VisibleFieldCount": 28,
		"RowsCount": 5
	},
	"NonQuery": 0,
	"IsNull": false
}

```

## Environment

```
.NET Core SDK version: 3.1.302
Microsoft.EntityFrameworkCore version: 3.1.6
EFCoreSecondLevelCacheInterceptor version: 1.8.2
```

## Example code/Steps to reproduce:
In startup
``` C# 
       serviceCollection
                .AddEFSecondLevelCache(opts => opts.UseCacheManagerCoreProvider().DisableLogging(false))
                .AddSingleton(typeof(ICacheManager<>), typeof(BaseCacheManager<>))
                .AddSingleton(typeof(ICacheManagerConfiguration),
                    new ConfigurationBuilder()
                        .WithMaxRetries(100)
                        .WithJsonSerializer(options.JsonSerializerSettings, options.JsonSerializerSettings)
                        .WithRedisConfiguration(RedisConfigurationKey, redisConnectionString)
                        .WithRedisCacheHandle(RedisConfigurationKey)
                        .WithExpiration(options.ExpirationMode, options.Timeout)
                        .Build());
```
``` C#
public JsonSerializerSettings JsonSerializerSettings { get; set; } = new JsonSerializerSettings
        {
            NullValueHandling = NullValueHandling.Ignore,
            ReferenceLoopHandling = ReferenceLoopHandling.Ignore,
            TypeNameHandling = TypeNameHandling.Auto,
            ContractResolver = new ContractResolver()
        };
```
The query
``` C#
_db.Set<CentreSchedule>
      .Cacheable()
      .FirstOrDefaultAsync(x => x.CentreId == someId, token);
```
## Output:

```
Exception message: `System.InvalidCastException: Unable to cast object of type 'System.String' to type 'System.TimeSpan'.`
Full Stack trace:
   at System.Data.Common.DbDataReader.GetFieldValue[T](Int32 ordinal)
   at lambda_method(Closure , QueryContext , DbDataReader , ResultContext , Int32[] , ResultCoordinator )
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)

```

**Comment by VahidN** [comment]
You should use [SpecialTypesConverter](https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/blob/master/src/Tests/EFCoreSecondLevelCacheInterceptor.Tests/Settings/EFServiceProvider.cs#L25) with it [this way](https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/blob/master/src/Tests/EFCoreSecondLevelCacheInterceptor.Tests/Settings/EFServiceProvider.cs#L212).

**Comment by jasonycw** [comment]
@VahidN Thanks for your suggestion, it works. 
But I would like to know why it was working before with `EFSecondLevelCache.Core` and not in `EFCoreSecondLevelCacheInterceptor`?

It doesn't seems like a `CacheManager.Core` problem since it was working with `EFSecondLevelCache.Core` and Newtonsoft.Json can properly deserialize TimeSpan by default or with my original `JsonSerializerSettings`.

Is there something change specific for `EFCoreSecondLevelCacheInterceptor`?

**Comment by VahidN** [comment]
It's duplicate of https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/issues/29#issuecomment-621354440

**Comment by jasonycw** [comment]
So it's because of the new `EFCoreSecondLevelCacheInterceptor` redis cache JSON format, causing the deserialize to fail(difference from the `EFSecondLevelCache.Core` implementation) and need extra handling in the `JsonSerializerSettings`.

Thanks!
