### ISSUE TITLE
How to force a  query to re-cache the data?

### ISSUE THREAD

**Issue by ikhalil-intel** [VahidN/EFCoreSecondLevelCacheInterceptor#54]
# Summary of the issue
I am getting an exception on specific data (callstack at the end), for some reason it looks like some int data in the cache is invalid. I can get around it by doing a try/catch and just querying the database on the catch, but I am wondering if there's a way to remove a specific cached entry.

In my specific case for example, I have this:

`                    
estCatInfoList = await osirisContext.estCatView
                       .Where(e => e.estID == estID)
                       .Cacheable(CacheExpirationMode.Absolute, TimeSpan.FromHours(24)) //Cache this query
                       .ToListAsync();
`

But because I do not know what's the EFCacheKey used for this query, I can't call InvalidateCacheDependencies(...).  Is there a way for me to generate that EFCacheKey? It would also be really useful to have a parameter in the Cacheable function to invalidate the cache and re-cache the result from the DB. 

Exception that I get:

System.FormatException: Input string was not in a correct format.
         at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
         at System.Number.ParseInt32(ReadOnlySpan`1 value, NumberStyles styles, NumberFormatInfo info)
         at System.String.System.IConvertible.ToInt32(IFormatProvider provider)
         at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
         at System.Convert.ChangeType(Object value, Type conversionType)
         at EFCoreSecondLevelCacheInterceptor.EFTableRowsDataReader.GetInt32(Int32 ordinal)

(I am using easy caching redis by the way)

**Comment by VahidN** [comment]
Read the readme file.
