### ISSUE TITLE
Models with List properties cause exception

### ISSUE THREAD

**Issue by adnan-kamili** [VahidN/EFCoreSecondLevelCacheInterceptor#58]
# Summary of the issue

When any entity which uses List in its properties is cached by Redis, it crashes with the error in output section. Sample entity:

```
    public class Product : BaseEntity
    {
        [Required]
        public string Name { get; set; }

        [Required]
        public string DisplayName { get; set; }

        public List<Item> Items { get; set; } = new List<Item>();
    }
```

## Environment

```
Microsoft.EntityFrameworkCore version: 3.1.10
EFCoreSecondLevelCacheInterceptor version: 2.0.1
```

## Output:

```
[14:49:35 DBG] [0HM4MKCT0EEJ0:00000009] - InstanceId: f847fe4e-73f1-4b63-afbe-ccc21217a6fb, Started @12/02/2020 09:18:06 UTC. Returning the cached TableRows[e24cc9e7-f856-40c9-ad54-cecc814d5ea1].
[14:49:35 ERR] [0HM4MKCT0EEJ0:00000009] - An exception occurred while iterating over the results of a query for context type 'MyWebApi.Repository.ApplicationDbContext'.
System.InvalidCastException: Unable to cast object of type 'System.String[]' to type 'System.Collections.Generic.List`1[System.String]'.
   at System.Data.Common.DbDataReader.GetFieldValue[T](Int32 ordinal)
   at lambda_method(Closure , QueryContext , DbDataReader , ResultContext , Int32[] , ResultCoordinator )
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
System.InvalidCastException: Unable to cast object of type 'System.String[]' to type 'System.Collections.Generic.List`1[System.String]'.
   at System.Data.Common.DbDataReader.GetFieldValue[T](Int32 ordinal)
   at lambda_method(Closure , QueryContext , DbDataReader , ResultContext , Int32[] , ResultCoordinator )
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
[14:49:35 DBG] [0HM4MKCT0EEJ0:00000009] - A data reader was disposed.
[14:49:35 DBG] [0HM4MKCT0EEJ0:00000009] - Closing connection to database 'my_db' on server 'tcp://localhost:5432'.
[14:49:35 DBG] [0HM4MKCT0EEJ0:00000009] - Closed connection to database 'my_db' on server 'tcp://localhost:5432'.
[14:49:35 ERR] [0HM4MKCT0EEJ0:00000009] - Unable to cast object of type 'System.String[]' to type 'System.Collections.Generic.List`1[System.String]'.
```

**Comment by VahidN** [comment]
If you are using the `EasyCaching` try adding this setting:
```
services.AddEasyCaching(option =>
            {
                option.WithJson(x =>
                {
                    x.NullValueHandling = NullValueHandling.Ignore;
                    x.ReferenceLoopHandling = ReferenceLoopHandling.Ignore;
                    x.TypeNameHandling = TypeNameHandling.Auto;
                    x.Converters = new List<JsonConverter>() {new SpecialTypesConverter()};
                }, "json");
```

The `SpecialTypesConverter` can be found [here](https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/blob/master/src/Tests/EFCoreSecondLevelCacheInterceptor.Tests/Settings/EFServiceProvider.cs#L26).

**Comment by adnan-kamili** [comment]
Thanks for the quick reply.

It seems the options you provided require Newtonsoft. I am not using Newtonsoft.

**Comment by VahidN** [comment]
So don't use this library. This is not suitable for you.
