### ISSUE TITLE
Supporting Model with list properties

### ISSUE THREAD

**Issue by faizan-kamili** [VahidN/EFCoreSecondLevelCacheInterceptor#59]
# Summary of the issue

First of all, I would like to congratulate you on this amazing project. It's so simple to use and highly performant. In addition to that we don't need to care about cache invalidation (that is amazing).

Now coming to the issue, we have setup this library and every thing is working as expected. But the models with List properties cause a crash. I found a similar issue:

https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/issues/58

I tried your suggestion but now the app crashes on startup complaining about a service resolution issue. It only happens when I add the "WithJson" code. We have installed Newtonsoft.Json package too.

## Environment

```
.NET Core SDK version: 3.1
Microsoft.EntityFrameworkCore version: 3.1.10
EFCoreSecondLevelCacheInterceptor version: 2.0.1
```

## Example code/Steps to reproduce:

```
services.AddEasyCaching(option =>
                    {
                        option.WithJson(option =>
                        {
                            option.NullValueHandling = NullValueHandling.Ignore;
                            option.ReferenceLoopHandling = ReferenceLoopHandling.Ignore;
                            option.TypeNameHandling = TypeNameHandling.Auto;
                            option.Converters = new List<JsonConverter>() { new SpecialTypesConverter() };
                        }, "json");
                        option.UseRedis(config =>
                        {
                            config.DBConfig.AllowAdmin = true;
                            config.DBConfig.Configuration = Configuration.Get<AppOptions>().Redis.Url;
                        }, providerName);
                    });
```

## Output:

```
4:38:12 FTL] [] - Application startup exception
System.Exception: Could not resolve a service of type 'MyWebApi.Repository.IRepository' for the parameter 'repository' of method 'Configure' on type 'MyWebApi.Startup'.
 ---> System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at System.Linq.Enumerable.Single[TSource](IEnumerable1 source, Func2 predicate)
   at EasyCaching.Redis.DefaultRedisCachingProvider..ctor(String name, IEnumerable1 dbProviders, IEnumerable1 serializers, RedisOptions options, ILoggerFactory loggerFactory)
   at EasyCaching.Redis.RedisOptionsExtension.<AddServices>b__3_1(IServiceProvider x)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitIEnumerable(IEnumerableCallSite enumerableCallSite, RuntimeResolverContext context)


```

**Comment by VahidN** [comment]
- You should use [ICollection](https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/blob/master/src/Tests/EFCoreSecondLevelCacheInterceptor.Tests.DataLayer/Entities/Blog.cs#L15) with EF-Core.
- Have you installed? 
```
dotnet add package EasyCaching.Serialization.Json --version 0.9.0
```
- You are not using `WithJson` in your `UseRedis` setting. Try adding:
```
config.SerializerName = "json";
```

**Comment by faizan-kamili** [comment]
Thanks for the prompt reply.

I added `config.SerializerName = "json"; `and it fixed the crash related to service resolution.

I also updated the model to use ICollection. I was using EasCaching related packages 1.1.0 and downgraded them to 0.9.0 (including the one you mentioned), but the model with collection property still crashes:

`System.InvalidCastException: Unable to cast object of type 'System.String[]' to type 'System.Collections.Generic.List`1[System.String]'.`

I used your SpecialTypesConverter class as is, do I need to update it?

**Comment by VahidN** [comment]
I have a lot of [tests here](https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/blob/master/src/Tests/EFCoreSecondLevelCacheInterceptor.Tests/Settings/EFServiceProvider.cs#L225) for testing the redis provider (without the JSON serilizer) and `ICollection`s. All of them are passing.

**Comment by VahidN** [comment]
P.S. 
I'm not going to waste my time for this, because I have working tests.
