### ISSUE TITLE
Unable to cast object of type 'System.Int64' to type 'System.UInt64'

### ISSUE THREAD

**Issue by Matcheryt** [VahidN/EFCoreSecondLevelCacheInterceptor#66]
# Summary of the issue
Using EFCore with SQLite database, when I call a method that retrieves a string from the database where the GuildId provided == GuildId on the database, I get an InvalidCastException.

## Environment
```
.NET Core SDK version: .NET 5.0
Microsoft.EntityFrameworkCore.Sqlite version: 5.0.1
EFCoreSecondLevelCacheInterceptor version: 2.3.0
```

## Example code/Steps to reproduce:

```csharp
public string GetGuildPrefix(ulong guildId)
{
  return Guilds.AsNoTracking().FirstOrDefault(x => x.GuildId == guildId)?.CustomPrefix ?? "-";
}
```

## Output:

```
Exception message: System.InvalidCastException: Unable to cast object of type 'System.Int64' to type 'System.UInt64'.

Full Stack trace: 
System.InvalidCastException: Unable to cast object of type 'System.Int64' to type 'System.UInt64'.
   at System.Data.Common.DbDataReader.GetFieldValue[T](Int32 ordinal)
   at lambda_method436(Closure , QueryContext , DbDataReader , ResultContext , SingleQueryResultCoordinator )
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.MoveNext()
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at System.Linq.Queryable.FirstOrDefault[TSource](IQueryable`1 source, Expression`1 predicate)
   at CobraBot.Database.BotContext.GetGuildPrefix(UInt64 guildId) in C:\Users\match\Documents\Visual Studio 2019\Projects\CobraDev\CobraBot\Database\BotContext.cs:line 42
   at CobraBot.Handlers.CommandHandler.HandleCommandAsync(SocketMessage rawMessage) in C:\Users\match\Documents\Visual Studio 2019\Projects\CobraDev\CobraBot\Handlers\CommandHandler.cs:line 64
   at Discord.EventExtensions.InvokeAsync[T](AsyncEvent`1 eventHandler, T arg)
   at Discord.WebSocket.DiscordSocketClient.TimeoutWrap(String name, Func`1 action)
```

**Comment by VahidN** [comment]
I have a working [ulong sample here](https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/blob/master/src/Tests/Issues/Issue9SQLiteInt32/Entities/Person.cs#L42) for SQLite.

**Comment by Matcheryt** [comment]
It only happens when I add the interceptor to the context, not sure what may be causing this.
Thanks anyway!

**Comment by yigityuksel** [comment]
I encountered a similar problem. The reason was related to the boolean property mapping in MYSQL. I had two different two fields(TINYINT(1) and BIT(1)) in the database to cast boolean. BIT(1) field causes the problem. In order to fix mapping, you need to specify the default data type in options.

`                    opts.UseMySql(connectionString, builder => builder.DefaultDataTypeMappings(m => 
                                m.WithClrBoolean(MySqlBooleanType.Bit1)))
                        .UseLazyLoadingProxies()
                        .AddInterceptors(provider.GetRequiredService<SecondLevelCacheInterceptor>());
`
